//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5 C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3 2013-02-21 18:05:38

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5")]
[System.CLSCompliant(false)]
public partial class aegiscriptLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__17=17;
	public const int T__18=18;
	public const int T__19=19;
	public const int T__20=20;
	public const int T__21=21;
	public const int T__22=22;
	public const int T__23=23;
	public const int T__24=24;
	public const int T__25=25;
	public const int T__26=26;
	public const int T__27=27;
	public const int T__28=28;
	public const int T__29=29;
	public const int T__30=30;
	public const int T__31=31;
	public const int T__32=32;
	public const int T__33=33;
	public const int T__34=34;
	public const int T__35=35;
	public const int T__36=36;
	public const int T__37=37;
	public const int T__38=38;
	public const int T__39=39;
	public const int T__40=40;
	public const int T__41=41;
	public const int T__42=42;
	public const int T__43=43;
	public const int T__44=44;
	public const int COMMENT=4;
	public const int DIGIT=5;
	public const int ESC_SEQ=6;
	public const int EXPONENT=7;
	public const int FLOAT=8;
	public const int HEX_DIGIT=9;
	public const int IDENT=10;
	public const int INTEGER=11;
	public const int LETTER=12;
	public const int MULTILINE_COMMENT=13;
	public const int OCTAL_ESC=14;
	public const int UNICODE_ESC=15;
	public const int WS=16;

    // delegates
    // delegators

	public aegiscriptLexer()
	{
		OnCreated();
	}

	public aegiscriptLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public aegiscriptLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__17();
	partial void LeaveRule_T__17();

	// $ANTLR start "T__17"
	[GrammarRule("T__17")]
	private void mT__17()
	{
		EnterRule_T__17();
		EnterRule("T__17", 1);
		TraceIn("T__17", 1);
		try
		{
			int _type = T__17;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:7:7: ( '(' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:7:9: '('
			{
			DebugLocation(7, 9);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__17", 1);
			LeaveRule("T__17", 1);
			LeaveRule_T__17();
		}
	}
	// $ANTLR end "T__17"

	partial void EnterRule_T__18();
	partial void LeaveRule_T__18();

	// $ANTLR start "T__18"
	[GrammarRule("T__18")]
	private void mT__18()
	{
		EnterRule_T__18();
		EnterRule("T__18", 2);
		TraceIn("T__18", 2);
		try
		{
			int _type = T__18;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:8:7: ( ')' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:8:9: ')'
			{
			DebugLocation(8, 9);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__18", 2);
			LeaveRule("T__18", 2);
			LeaveRule_T__18();
		}
	}
	// $ANTLR end "T__18"

	partial void EnterRule_T__19();
	partial void LeaveRule_T__19();

	// $ANTLR start "T__19"
	[GrammarRule("T__19")]
	private void mT__19()
	{
		EnterRule_T__19();
		EnterRule("T__19", 3);
		TraceIn("T__19", 3);
		try
		{
			int _type = T__19;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:9:7: ( '*' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:9:9: '*'
			{
			DebugLocation(9, 9);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__19", 3);
			LeaveRule("T__19", 3);
			LeaveRule_T__19();
		}
	}
	// $ANTLR end "T__19"

	partial void EnterRule_T__20();
	partial void LeaveRule_T__20();

	// $ANTLR start "T__20"
	[GrammarRule("T__20")]
	private void mT__20()
	{
		EnterRule_T__20();
		EnterRule("T__20", 4);
		TraceIn("T__20", 4);
		try
		{
			int _type = T__20;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:10:7: ( '+' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:10:9: '+'
			{
			DebugLocation(10, 9);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__20", 4);
			LeaveRule("T__20", 4);
			LeaveRule_T__20();
		}
	}
	// $ANTLR end "T__20"

	partial void EnterRule_T__21();
	partial void LeaveRule_T__21();

	// $ANTLR start "T__21"
	[GrammarRule("T__21")]
	private void mT__21()
	{
		EnterRule_T__21();
		EnterRule("T__21", 5);
		TraceIn("T__21", 5);
		try
		{
			int _type = T__21;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:11:7: ( ',' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:11:9: ','
			{
			DebugLocation(11, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__21", 5);
			LeaveRule("T__21", 5);
			LeaveRule_T__21();
		}
	}
	// $ANTLR end "T__21"

	partial void EnterRule_T__22();
	partial void LeaveRule_T__22();

	// $ANTLR start "T__22"
	[GrammarRule("T__22")]
	private void mT__22()
	{
		EnterRule_T__22();
		EnterRule("T__22", 6);
		TraceIn("T__22", 6);
		try
		{
			int _type = T__22;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:12:7: ( '-' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:12:9: '-'
			{
			DebugLocation(12, 9);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__22", 6);
			LeaveRule("T__22", 6);
			LeaveRule_T__22();
		}
	}
	// $ANTLR end "T__22"

	partial void EnterRule_T__23();
	partial void LeaveRule_T__23();

	// $ANTLR start "T__23"
	[GrammarRule("T__23")]
	private void mT__23()
	{
		EnterRule_T__23();
		EnterRule("T__23", 7);
		TraceIn("T__23", 7);
		try
		{
			int _type = T__23;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:13:7: ( '/' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:13:9: '/'
			{
			DebugLocation(13, 9);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__23", 7);
			LeaveRule("T__23", 7);
			LeaveRule_T__23();
		}
	}
	// $ANTLR end "T__23"

	partial void EnterRule_T__24();
	partial void LeaveRule_T__24();

	// $ANTLR start "T__24"
	[GrammarRule("T__24")]
	private void mT__24()
	{
		EnterRule_T__24();
		EnterRule("T__24", 8);
		TraceIn("T__24", 8);
		try
		{
			int _type = T__24;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:14:7: ( '/=' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:14:9: '/='
			{
			DebugLocation(14, 9);
			Match("/="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__24", 8);
			LeaveRule("T__24", 8);
			LeaveRule_T__24();
		}
	}
	// $ANTLR end "T__24"

	partial void EnterRule_T__25();
	partial void LeaveRule_T__25();

	// $ANTLR start "T__25"
	[GrammarRule("T__25")]
	private void mT__25()
	{
		EnterRule_T__25();
		EnterRule("T__25", 9);
		TraceIn("T__25", 9);
		try
		{
			int _type = T__25;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:15:7: ( ':' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:15:9: ':'
			{
			DebugLocation(15, 9);
			Match(':'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__25", 9);
			LeaveRule("T__25", 9);
			LeaveRule_T__25();
		}
	}
	// $ANTLR end "T__25"

	partial void EnterRule_T__26();
	partial void LeaveRule_T__26();

	// $ANTLR start "T__26"
	[GrammarRule("T__26")]
	private void mT__26()
	{
		EnterRule_T__26();
		EnterRule("T__26", 10);
		TraceIn("T__26", 10);
		try
		{
			int _type = T__26;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:16:7: ( ';' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:16:9: ';'
			{
			DebugLocation(16, 9);
			Match(';'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__26", 10);
			LeaveRule("T__26", 10);
			LeaveRule_T__26();
		}
	}
	// $ANTLR end "T__26"

	partial void EnterRule_T__27();
	partial void LeaveRule_T__27();

	// $ANTLR start "T__27"
	[GrammarRule("T__27")]
	private void mT__27()
	{
		EnterRule_T__27();
		EnterRule("T__27", 11);
		TraceIn("T__27", 11);
		try
		{
			int _type = T__27;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:17:7: ( '<' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:17:9: '<'
			{
			DebugLocation(17, 9);
			Match('<'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__27", 11);
			LeaveRule("T__27", 11);
			LeaveRule_T__27();
		}
	}
	// $ANTLR end "T__27"

	partial void EnterRule_T__28();
	partial void LeaveRule_T__28();

	// $ANTLR start "T__28"
	[GrammarRule("T__28")]
	private void mT__28()
	{
		EnterRule_T__28();
		EnterRule("T__28", 12);
		TraceIn("T__28", 12);
		try
		{
			int _type = T__28;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:18:7: ( '<=' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:18:9: '<='
			{
			DebugLocation(18, 9);
			Match("<="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__28", 12);
			LeaveRule("T__28", 12);
			LeaveRule_T__28();
		}
	}
	// $ANTLR end "T__28"

	partial void EnterRule_T__29();
	partial void LeaveRule_T__29();

	// $ANTLR start "T__29"
	[GrammarRule("T__29")]
	private void mT__29()
	{
		EnterRule_T__29();
		EnterRule("T__29", 13);
		TraceIn("T__29", 13);
		try
		{
			int _type = T__29;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:19:7: ( '=' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:19:9: '='
			{
			DebugLocation(19, 9);
			Match('='); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__29", 13);
			LeaveRule("T__29", 13);
			LeaveRule_T__29();
		}
	}
	// $ANTLR end "T__29"

	partial void EnterRule_T__30();
	partial void LeaveRule_T__30();

	// $ANTLR start "T__30"
	[GrammarRule("T__30")]
	private void mT__30()
	{
		EnterRule_T__30();
		EnterRule("T__30", 14);
		TraceIn("T__30", 14);
		try
		{
			int _type = T__30;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:20:7: ( '>' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:20:9: '>'
			{
			DebugLocation(20, 9);
			Match('>'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__30", 14);
			LeaveRule("T__30", 14);
			LeaveRule_T__30();
		}
	}
	// $ANTLR end "T__30"

	partial void EnterRule_T__31();
	partial void LeaveRule_T__31();

	// $ANTLR start "T__31"
	[GrammarRule("T__31")]
	private void mT__31()
	{
		EnterRule_T__31();
		EnterRule("T__31", 15);
		TraceIn("T__31", 15);
		try
		{
			int _type = T__31;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:21:7: ( '>=' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:21:9: '>='
			{
			DebugLocation(21, 9);
			Match(">="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__31", 15);
			LeaveRule("T__31", 15);
			LeaveRule_T__31();
		}
	}
	// $ANTLR end "T__31"

	partial void EnterRule_T__32();
	partial void LeaveRule_T__32();

	// $ANTLR start "T__32"
	[GrammarRule("T__32")]
	private void mT__32()
	{
		EnterRule_T__32();
		EnterRule("T__32", 16);
		TraceIn("T__32", 16);
		try
		{
			int _type = T__32;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:22:7: ( 'Integer' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:22:9: 'Integer'
			{
			DebugLocation(22, 9);
			Match("Integer"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__32", 16);
			LeaveRule("T__32", 16);
			LeaveRule_T__32();
		}
	}
	// $ANTLR end "T__32"

	partial void EnterRule_T__33();
	partial void LeaveRule_T__33();

	// $ANTLR start "T__33"
	[GrammarRule("T__33")]
	private void mT__33()
	{
		EnterRule_T__33();
		EnterRule("T__33", 17);
		TraceIn("T__33", 17);
		try
		{
			int _type = T__33;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:23:7: ( 'and' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:23:9: 'and'
			{
			DebugLocation(23, 9);
			Match("and"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__33", 17);
			LeaveRule("T__33", 17);
			LeaveRule_T__33();
		}
	}
	// $ANTLR end "T__33"

	partial void EnterRule_T__34();
	partial void LeaveRule_T__34();

	// $ANTLR start "T__34"
	[GrammarRule("T__34")]
	private void mT__34()
	{
		EnterRule_T__34();
		EnterRule("T__34", 18);
		TraceIn("T__34", 18);
		try
		{
			int _type = T__34;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:24:7: ( 'begin' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:24:9: 'begin'
			{
			DebugLocation(24, 9);
			Match("begin"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__34", 18);
			LeaveRule("T__34", 18);
			LeaveRule_T__34();
		}
	}
	// $ANTLR end "T__34"

	partial void EnterRule_T__35();
	partial void LeaveRule_T__35();

	// $ANTLR start "T__35"
	[GrammarRule("T__35")]
	private void mT__35()
	{
		EnterRule_T__35();
		EnterRule("T__35", 19);
		TraceIn("T__35", 19);
		try
		{
			int _type = T__35;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:25:7: ( 'constant' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:25:9: 'constant'
			{
			DebugLocation(25, 9);
			Match("constant"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__35", 19);
			LeaveRule("T__35", 19);
			LeaveRule_T__35();
		}
	}
	// $ANTLR end "T__35"

	partial void EnterRule_T__36();
	partial void LeaveRule_T__36();

	// $ANTLR start "T__36"
	[GrammarRule("T__36")]
	private void mT__36()
	{
		EnterRule_T__36();
		EnterRule("T__36", 20);
		TraceIn("T__36", 20);
		try
		{
			int _type = T__36;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:26:7: ( 'else' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:26:9: 'else'
			{
			DebugLocation(26, 9);
			Match("else"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__36", 20);
			LeaveRule("T__36", 20);
			LeaveRule_T__36();
		}
	}
	// $ANTLR end "T__36"

	partial void EnterRule_T__37();
	partial void LeaveRule_T__37();

	// $ANTLR start "T__37"
	[GrammarRule("T__37")]
	private void mT__37()
	{
		EnterRule_T__37();
		EnterRule("T__37", 21);
		TraceIn("T__37", 21);
		try
		{
			int _type = T__37;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:27:7: ( 'elsif' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:27:9: 'elsif'
			{
			DebugLocation(27, 9);
			Match("elsif"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__37", 21);
			LeaveRule("T__37", 21);
			LeaveRule_T__37();
		}
	}
	// $ANTLR end "T__37"

	partial void EnterRule_T__38();
	partial void LeaveRule_T__38();

	// $ANTLR start "T__38"
	[GrammarRule("T__38")]
	private void mT__38()
	{
		EnterRule_T__38();
		EnterRule("T__38", 22);
		TraceIn("T__38", 22);
		try
		{
			int _type = T__38;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:28:7: ( 'end' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:28:9: 'end'
			{
			DebugLocation(28, 9);
			Match("end"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__38", 22);
			LeaveRule("T__38", 22);
			LeaveRule_T__38();
		}
	}
	// $ANTLR end "T__38"

	partial void EnterRule_T__39();
	partial void LeaveRule_T__39();

	// $ANTLR start "T__39"
	[GrammarRule("T__39")]
	private void mT__39()
	{
		EnterRule_T__39();
		EnterRule("T__39", 23);
		TraceIn("T__39", 23);
		try
		{
			int _type = T__39;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:29:7: ( 'if' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:29:9: 'if'
			{
			DebugLocation(29, 9);
			Match("if"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__39", 23);
			LeaveRule("T__39", 23);
			LeaveRule_T__39();
		}
	}
	// $ANTLR end "T__39"

	partial void EnterRule_T__40();
	partial void LeaveRule_T__40();

	// $ANTLR start "T__40"
	[GrammarRule("T__40")]
	private void mT__40()
	{
		EnterRule_T__40();
		EnterRule("T__40", 24);
		TraceIn("T__40", 24);
		try
		{
			int _type = T__40;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:30:7: ( 'mod' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:30:9: 'mod'
			{
			DebugLocation(30, 9);
			Match("mod"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__40", 24);
			LeaveRule("T__40", 24);
			LeaveRule_T__40();
		}
	}
	// $ANTLR end "T__40"

	partial void EnterRule_T__41();
	partial void LeaveRule_T__41();

	// $ANTLR start "T__41"
	[GrammarRule("T__41")]
	private void mT__41()
	{
		EnterRule_T__41();
		EnterRule("T__41", 25);
		TraceIn("T__41", 25);
		try
		{
			int _type = T__41;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:31:7: ( 'not' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:31:9: 'not'
			{
			DebugLocation(31, 9);
			Match("not"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__41", 25);
			LeaveRule("T__41", 25);
			LeaveRule_T__41();
		}
	}
	// $ANTLR end "T__41"

	partial void EnterRule_T__42();
	partial void LeaveRule_T__42();

	// $ANTLR start "T__42"
	[GrammarRule("T__42")]
	private void mT__42()
	{
		EnterRule_T__42();
		EnterRule("T__42", 26);
		TraceIn("T__42", 26);
		try
		{
			int _type = T__42;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:32:7: ( 'or' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:32:9: 'or'
			{
			DebugLocation(32, 9);
			Match("or"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__42", 26);
			LeaveRule("T__42", 26);
			LeaveRule_T__42();
		}
	}
	// $ANTLR end "T__42"

	partial void EnterRule_T__43();
	partial void LeaveRule_T__43();

	// $ANTLR start "T__43"
	[GrammarRule("T__43")]
	private void mT__43()
	{
		EnterRule_T__43();
		EnterRule("T__43", 27);
		TraceIn("T__43", 27);
		try
		{
			int _type = T__43;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:33:7: ( 'var' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:33:9: 'var'
			{
			DebugLocation(33, 9);
			Match("var"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__43", 27);
			LeaveRule("T__43", 27);
			LeaveRule_T__43();
		}
	}
	// $ANTLR end "T__43"

	partial void EnterRule_T__44();
	partial void LeaveRule_T__44();

	// $ANTLR start "T__44"
	[GrammarRule("T__44")]
	private void mT__44()
	{
		EnterRule_T__44();
		EnterRule("T__44", 28);
		TraceIn("T__44", 28);
		try
		{
			int _type = T__44;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:34:7: ( 'while' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:34:9: 'while'
			{
			DebugLocation(34, 9);
			Match("while"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__44", 28);
			LeaveRule("T__44", 28);
			LeaveRule_T__44();
		}
	}
	// $ANTLR end "T__44"

	partial void EnterRule_FLOAT();
	partial void LeaveRule_FLOAT();

	// $ANTLR start "FLOAT"
	[GrammarRule("FLOAT")]
	private void mFLOAT()
	{
		EnterRule_FLOAT();
		EnterRule("FLOAT", 29);
		TraceIn("FLOAT", 29);
		try
		{
			int _type = FLOAT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:92:5: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT )
			int alt7=3;
			try { DebugEnterDecision(7, false);
			try
			{
				alt7 = dfa7.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:92:9: ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )?
				{
				DebugLocation(92, 9);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:92:9: ( '0' .. '9' )+
				int cnt1=0;
				try { DebugEnterSubRule(1);
				while (true)
				{
					int alt1=2;
					try { DebugEnterDecision(1, false);
					int LA1_1 = input.LA(1);

					if (((LA1_1>='0' && LA1_1<='9')))
					{
						alt1 = 1;
					}


					} finally { DebugExitDecision(1); }
					switch (alt1)
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
						{
						DebugLocation(92, 9);
						input.Consume();


						}
						break;

					default:
						if (cnt1 >= 1)
							goto loop1;

						EarlyExitException eee1 = new EarlyExitException( 1, input );
						DebugRecognitionException(eee1);
						throw eee1;
					}
					cnt1++;
				}
				loop1:
					;

				} finally { DebugExitSubRule(1); }

				DebugLocation(92, 21);
				Match('.'); 
				DebugLocation(92, 25);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:92:25: ( '0' .. '9' )*
				try { DebugEnterSubRule(2);
				while (true)
				{
					int alt2=2;
					try { DebugEnterDecision(2, false);
					int LA2_1 = input.LA(1);

					if (((LA2_1>='0' && LA2_1<='9')))
					{
						alt2 = 1;
					}


					} finally { DebugExitDecision(2); }
					switch ( alt2 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
						{
						DebugLocation(92, 25);
						input.Consume();


						}
						break;

					default:
						goto loop2;
					}
				}

				loop2:
					;

				} finally { DebugExitSubRule(2); }

				DebugLocation(92, 37);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:92:37: ( EXPONENT )?
				int alt3=2;
				try { DebugEnterSubRule(3);
				try { DebugEnterDecision(3, false);
				int LA3_1 = input.LA(1);

				if ((LA3_1=='E'||LA3_1=='e'))
				{
					alt3 = 1;
				}
				} finally { DebugExitDecision(3); }
				switch (alt3)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:92:37: EXPONENT
					{
					DebugLocation(92, 37);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(3); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:93:9: '.' ( '0' .. '9' )+ ( EXPONENT )?
				{
				DebugLocation(93, 9);
				Match('.'); 
				DebugLocation(93, 13);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:93:13: ( '0' .. '9' )+
				int cnt4=0;
				try { DebugEnterSubRule(4);
				while (true)
				{
					int alt4=2;
					try { DebugEnterDecision(4, false);
					int LA4_1 = input.LA(1);

					if (((LA4_1>='0' && LA4_1<='9')))
					{
						alt4 = 1;
					}


					} finally { DebugExitDecision(4); }
					switch (alt4)
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
						{
						DebugLocation(93, 13);
						input.Consume();


						}
						break;

					default:
						if (cnt4 >= 1)
							goto loop4;

						EarlyExitException eee4 = new EarlyExitException( 4, input );
						DebugRecognitionException(eee4);
						throw eee4;
					}
					cnt4++;
				}
				loop4:
					;

				} finally { DebugExitSubRule(4); }

				DebugLocation(93, 25);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:93:25: ( EXPONENT )?
				int alt5=2;
				try { DebugEnterSubRule(5);
				try { DebugEnterDecision(5, false);
				int LA5_1 = input.LA(1);

				if ((LA5_1=='E'||LA5_1=='e'))
				{
					alt5 = 1;
				}
				} finally { DebugExitDecision(5); }
				switch (alt5)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:93:25: EXPONENT
					{
					DebugLocation(93, 25);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(5); }


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:94:9: ( '0' .. '9' )+ EXPONENT
				{
				DebugLocation(94, 9);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:94:9: ( '0' .. '9' )+
				int cnt6=0;
				try { DebugEnterSubRule(6);
				while (true)
				{
					int alt6=2;
					try { DebugEnterDecision(6, false);
					int LA6_1 = input.LA(1);

					if (((LA6_1>='0' && LA6_1<='9')))
					{
						alt6 = 1;
					}


					} finally { DebugExitDecision(6); }
					switch (alt6)
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
						{
						DebugLocation(94, 9);
						input.Consume();


						}
						break;

					default:
						if (cnt6 >= 1)
							goto loop6;

						EarlyExitException eee6 = new EarlyExitException( 6, input );
						DebugRecognitionException(eee6);
						throw eee6;
					}
					cnt6++;
				}
				loop6:
					;

				} finally { DebugExitSubRule(6); }

				DebugLocation(94, 21);
				mEXPONENT(); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FLOAT", 29);
			LeaveRule("FLOAT", 29);
			LeaveRule_FLOAT();
		}
	}
	// $ANTLR end "FLOAT"

	partial void EnterRule_MULTILINE_COMMENT();
	partial void LeaveRule_MULTILINE_COMMENT();

	// $ANTLR start "MULTILINE_COMMENT"
	[GrammarRule("MULTILINE_COMMENT")]
	private void mMULTILINE_COMMENT()
	{
		EnterRule_MULTILINE_COMMENT();
		EnterRule("MULTILINE_COMMENT", 30);
		TraceIn("MULTILINE_COMMENT", 30);
		try
		{
			int _type = MULTILINE_COMMENT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:97:19: ( '/*' ( . )* '*/' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:97:21: '/*' ( . )* '*/'
			{
			DebugLocation(97, 21);
			Match("/*"); 

			DebugLocation(97, 26);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:97:26: ( . )*
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				int LA8_1 = input.LA(1);

				if ((LA8_1=='*'))
				{
					int LA8_2 = input.LA(2);

					if ((LA8_2=='/'))
					{
						alt8 = 2;
					}
					else if (((LA8_2>='\u0000' && LA8_2<='.')||(LA8_2>='0' && LA8_2<='\uFFFF')))
					{
						alt8 = 1;
					}


				}
				else if (((LA8_1>='\u0000' && LA8_1<=')')||(LA8_1>='+' && LA8_1<='\uFFFF')))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch ( alt8 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:97:26: .
					{
					DebugLocation(97, 26);
					MatchAny(); 

					}
					break;

				default:
					goto loop8;
				}
			}

			loop8:
				;

			} finally { DebugExitSubRule(8); }

			DebugLocation(97, 29);
			Match("*/"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("MULTILINE_COMMENT", 30);
			LeaveRule("MULTILINE_COMMENT", 30);
			LeaveRule_MULTILINE_COMMENT();
		}
	}
	// $ANTLR end "MULTILINE_COMMENT"

	partial void EnterRule_EXPONENT();
	partial void LeaveRule_EXPONENT();

	// $ANTLR start "EXPONENT"
	[GrammarRule("EXPONENT")]
	private void mEXPONENT()
	{
		EnterRule_EXPONENT();
		EnterRule("EXPONENT", 31);
		TraceIn("EXPONENT", 31);
		try
		{
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:101:10: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:101:12: ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+
			{
			DebugLocation(101, 12);
			if (input.LA(1)=='E'||input.LA(1)=='e')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(101, 22);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:101:22: ( '+' | '-' )?
			int alt9=2;
			try { DebugEnterSubRule(9);
			try { DebugEnterDecision(9, false);
			int LA9_1 = input.LA(1);

			if ((LA9_1=='+'||LA9_1=='-'))
			{
				alt9 = 1;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
				{
				DebugLocation(101, 22);
				input.Consume();


				}
				break;

			}
			} finally { DebugExitSubRule(9); }

			DebugLocation(101, 33);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:101:33: ( '0' .. '9' )+
			int cnt10=0;
			try { DebugEnterSubRule(10);
			while (true)
			{
				int alt10=2;
				try { DebugEnterDecision(10, false);
				int LA10_1 = input.LA(1);

				if (((LA10_1>='0' && LA10_1<='9')))
				{
					alt10 = 1;
				}


				} finally { DebugExitDecision(10); }
				switch (alt10)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
					{
					DebugLocation(101, 33);
					input.Consume();


					}
					break;

				default:
					if (cnt10 >= 1)
						goto loop10;

					EarlyExitException eee10 = new EarlyExitException( 10, input );
					DebugRecognitionException(eee10);
					throw eee10;
				}
				cnt10++;
			}
			loop10:
				;

			} finally { DebugExitSubRule(10); }


			}

		}
		finally
		{
			TraceOut("EXPONENT", 31);
			LeaveRule("EXPONENT", 31);
			LeaveRule_EXPONENT();
		}
	}
	// $ANTLR end "EXPONENT"

	partial void EnterRule_HEX_DIGIT();
	partial void LeaveRule_HEX_DIGIT();

	// $ANTLR start "HEX_DIGIT"
	[GrammarRule("HEX_DIGIT")]
	private void mHEX_DIGIT()
	{
		EnterRule_HEX_DIGIT();
		EnterRule("HEX_DIGIT", 32);
		TraceIn("HEX_DIGIT", 32);
		try
		{
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:104:11: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
			{
			DebugLocation(104, 11);
			if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='F')||(input.LA(1)>='a' && input.LA(1)<='f'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("HEX_DIGIT", 32);
			LeaveRule("HEX_DIGIT", 32);
			LeaveRule_HEX_DIGIT();
		}
	}
	// $ANTLR end "HEX_DIGIT"

	partial void EnterRule_ESC_SEQ();
	partial void LeaveRule_ESC_SEQ();

	// $ANTLR start "ESC_SEQ"
	[GrammarRule("ESC_SEQ")]
	private void mESC_SEQ()
	{
		EnterRule_ESC_SEQ();
		EnterRule("ESC_SEQ", 33);
		TraceIn("ESC_SEQ", 33);
		try
		{
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:108:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) | UNICODE_ESC | OCTAL_ESC )
			int alt11=3;
			try { DebugEnterDecision(11, false);
			int LA11_1 = input.LA(1);

			if ((LA11_1=='\\'))
			{
				switch (input.LA(2))
				{
				case '\"':
				case '\'':
				case '\\':
				case 'b':
				case 'f':
				case 'n':
				case 'r':
				case 't':
					{
					alt11 = 1;
					}
					break;
				case 'u':
					{
					alt11 = 2;
					}
					break;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
					{
					alt11 = 3;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 11, 1, input, 2);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 11, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(11); }
			switch (alt11)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:108:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
				{
				DebugLocation(108, 9);
				Match('\\'); 
				DebugLocation(108, 14);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:109:9: UNICODE_ESC
				{
				DebugLocation(109, 9);
				mUNICODE_ESC(); 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:110:9: OCTAL_ESC
				{
				DebugLocation(110, 9);
				mOCTAL_ESC(); 

				}
				break;

			}
		}
		finally
		{
			TraceOut("ESC_SEQ", 33);
			LeaveRule("ESC_SEQ", 33);
			LeaveRule_ESC_SEQ();
		}
	}
	// $ANTLR end "ESC_SEQ"

	partial void EnterRule_OCTAL_ESC();
	partial void LeaveRule_OCTAL_ESC();

	// $ANTLR start "OCTAL_ESC"
	[GrammarRule("OCTAL_ESC")]
	private void mOCTAL_ESC()
	{
		EnterRule_OCTAL_ESC();
		EnterRule("OCTAL_ESC", 34);
		TraceIn("OCTAL_ESC", 34);
		try
		{
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:115:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )
			int alt12=3;
			try { DebugEnterDecision(12, false);
			int LA12_1 = input.LA(1);

			if ((LA12_1=='\\'))
			{
				int LA12_2 = input.LA(2);

				if (((LA12_2>='0' && LA12_2<='3')))
				{
					int LA12_3 = input.LA(3);

					if (((LA12_3>='0' && LA12_3<='7')))
					{
						int LA12_4 = input.LA(4);

						if (((LA12_4>='0' && LA12_4<='7')))
						{
							alt12 = 1;
						}
						else
						{
							alt12 = 2;
						}
					}
					else
					{
						alt12 = 3;
					}
				}
				else if (((LA12_2>='4' && LA12_2<='7')))
				{
					int LA12_3 = input.LA(3);

					if (((LA12_3>='0' && LA12_3<='7')))
					{
						alt12 = 2;
					}
					else
					{
						alt12 = 3;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 12, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 12, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(12); }
			switch (alt12)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:115:9: '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(115, 9);
				Match('\\'); 
				DebugLocation(115, 14);
				input.Consume();

				DebugLocation(115, 25);
				input.Consume();

				DebugLocation(115, 36);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:116:9: '\\\\' ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(116, 9);
				Match('\\'); 
				DebugLocation(116, 14);
				input.Consume();

				DebugLocation(116, 25);
				input.Consume();


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:117:9: '\\\\' ( '0' .. '7' )
				{
				DebugLocation(117, 9);
				Match('\\'); 
				DebugLocation(117, 14);
				input.Consume();


				}
				break;

			}
		}
		finally
		{
			TraceOut("OCTAL_ESC", 34);
			LeaveRule("OCTAL_ESC", 34);
			LeaveRule_OCTAL_ESC();
		}
	}
	// $ANTLR end "OCTAL_ESC"

	partial void EnterRule_UNICODE_ESC();
	partial void LeaveRule_UNICODE_ESC();

	// $ANTLR start "UNICODE_ESC"
	[GrammarRule("UNICODE_ESC")]
	private void mUNICODE_ESC()
	{
		EnterRule_UNICODE_ESC();
		EnterRule("UNICODE_ESC", 35);
		TraceIn("UNICODE_ESC", 35);
		try
		{
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:122:5: ( '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:122:9: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT
			{
			DebugLocation(122, 9);
			Match('\\'); 
			DebugLocation(122, 14);
			Match('u'); 
			DebugLocation(122, 18);
			mHEX_DIGIT(); 
			DebugLocation(122, 28);
			mHEX_DIGIT(); 
			DebugLocation(122, 38);
			mHEX_DIGIT(); 
			DebugLocation(122, 48);
			mHEX_DIGIT(); 

			}

		}
		finally
		{
			TraceOut("UNICODE_ESC", 35);
			LeaveRule("UNICODE_ESC", 35);
			LeaveRule_UNICODE_ESC();
		}
	}
	// $ANTLR end "UNICODE_ESC"

	partial void EnterRule_LETTER();
	partial void LeaveRule_LETTER();

	// $ANTLR start "LETTER"
	[GrammarRule("LETTER")]
	private void mLETTER()
	{
		EnterRule_LETTER();
		EnterRule("LETTER", 36);
		TraceIn("LETTER", 36);
		try
		{
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:123:17: ( ( 'a' .. 'z' | 'A' .. 'Z' ) )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
			{
			DebugLocation(123, 17);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("LETTER", 36);
			LeaveRule("LETTER", 36);
			LeaveRule_LETTER();
		}
	}
	// $ANTLR end "LETTER"

	partial void EnterRule_DIGIT();
	partial void LeaveRule_DIGIT();

	// $ANTLR start "DIGIT"
	[GrammarRule("DIGIT")]
	private void mDIGIT()
	{
		EnterRule_DIGIT();
		EnterRule("DIGIT", 37);
		TraceIn("DIGIT", 37);
		try
		{
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:124:16: ( '0' .. '9' )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
			{
			DebugLocation(124, 16);
			if ((input.LA(1)>='0' && input.LA(1)<='9'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("DIGIT", 37);
			LeaveRule("DIGIT", 37);
			LeaveRule_DIGIT();
		}
	}
	// $ANTLR end "DIGIT"

	partial void EnterRule_INTEGER();
	partial void LeaveRule_INTEGER();

	// $ANTLR start "INTEGER"
	[GrammarRule("INTEGER")]
	private void mINTEGER()
	{
		EnterRule_INTEGER();
		EnterRule("INTEGER", 38);
		TraceIn("INTEGER", 38);
		try
		{
			int _type = INTEGER;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:125:9: ( ( DIGIT )+ )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:125:11: ( DIGIT )+
			{
			DebugLocation(125, 11);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:125:11: ( DIGIT )+
			int cnt13=0;
			try { DebugEnterSubRule(13);
			while (true)
			{
				int alt13=2;
				try { DebugEnterDecision(13, false);
				int LA13_1 = input.LA(1);

				if (((LA13_1>='0' && LA13_1<='9')))
				{
					alt13 = 1;
				}


				} finally { DebugExitDecision(13); }
				switch (alt13)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
					{
					DebugLocation(125, 11);
					input.Consume();


					}
					break;

				default:
					if (cnt13 >= 1)
						goto loop13;

					EarlyExitException eee13 = new EarlyExitException( 13, input );
					DebugRecognitionException(eee13);
					throw eee13;
				}
				cnt13++;
			}
			loop13:
				;

			} finally { DebugExitSubRule(13); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INTEGER", 38);
			LeaveRule("INTEGER", 38);
			LeaveRule_INTEGER();
		}
	}
	// $ANTLR end "INTEGER"

	partial void EnterRule_IDENT();
	partial void LeaveRule_IDENT();

	// $ANTLR start "IDENT"
	[GrammarRule("IDENT")]
	private void mIDENT()
	{
		EnterRule_IDENT();
		EnterRule("IDENT", 39);
		TraceIn("IDENT", 39);
		try
		{
			int _type = IDENT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:126:7: ( LETTER ( LETTER | DIGIT )* )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:126:9: LETTER ( LETTER | DIGIT )*
			{
			DebugLocation(126, 9);
			mLETTER(); 
			DebugLocation(126, 16);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:126:16: ( LETTER | DIGIT )*
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=2;
				try { DebugEnterDecision(14, false);
				int LA14_1 = input.LA(1);

				if (((LA14_1>='0' && LA14_1<='9')||(LA14_1>='A' && LA14_1<='Z')||(LA14_1>='a' && LA14_1<='z')))
				{
					alt14 = 1;
				}


				} finally { DebugExitDecision(14); }
				switch ( alt14 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
					{
					DebugLocation(126, 16);
					input.Consume();


					}
					break;

				default:
					goto loop14;
				}
			}

			loop14:
				;

			} finally { DebugExitSubRule(14); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("IDENT", 39);
			LeaveRule("IDENT", 39);
			LeaveRule_IDENT();
		}
	}
	// $ANTLR end "IDENT"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 40);
		TraceIn("WS", 40);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:127:4: ( ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+ )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:127:6: ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+
			{
			DebugLocation(127, 6);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:127:6: ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+
			int cnt15=0;
			try { DebugEnterSubRule(15);
			while (true)
			{
				int alt15=2;
				try { DebugEnterDecision(15, false);
				int LA15_1 = input.LA(1);

				if (((LA15_1>='\t' && LA15_1<='\n')||(LA15_1>='\f' && LA15_1<='\r')||LA15_1==' '))
				{
					alt15 = 1;
				}


				} finally { DebugExitDecision(15); }
				switch (alt15)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:
					{
					DebugLocation(127, 6);
					input.Consume();


					}
					break;

				default:
					if (cnt15 >= 1)
						goto loop15;

					EarlyExitException eee15 = new EarlyExitException( 15, input );
					DebugRecognitionException(eee15);
					throw eee15;
				}
				cnt15++;
			}
			loop15:
				;

			} finally { DebugExitSubRule(15); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 40);
			LeaveRule("WS", 40);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_COMMENT();
	partial void LeaveRule_COMMENT();

	// $ANTLR start "COMMENT"
	[GrammarRule("COMMENT")]
	private void mCOMMENT()
	{
		EnterRule_COMMENT();
		EnterRule("COMMENT", 41);
		TraceIn("COMMENT", 41);
		try
		{
			int _type = COMMENT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:128:9: ( '//' ( . )* ( '\\n' | '\\r' ) )
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:128:11: '//' ( . )* ( '\\n' | '\\r' )
			{
			DebugLocation(128, 11);
			Match("//"); 

			DebugLocation(128, 16);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:128:16: ( . )*
			try { DebugEnterSubRule(16);
			while (true)
			{
				int alt16=2;
				try { DebugEnterDecision(16, false);
				int LA16_1 = input.LA(1);

				if ((LA16_1=='\n'||LA16_1=='\r'))
				{
					alt16 = 2;
				}
				else if (((LA16_1>='\u0000' && LA16_1<='\t')||(LA16_1>='\u000B' && LA16_1<='\f')||(LA16_1>='\u000E' && LA16_1<='\uFFFF')))
				{
					alt16 = 1;
				}


				} finally { DebugExitDecision(16); }
				switch ( alt16 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:128:16: .
					{
					DebugLocation(128, 16);
					MatchAny(); 

					}
					break;

				default:
					goto loop16;
				}
			}

			loop16:
				;

			} finally { DebugExitSubRule(16); }

			DebugLocation(128, 19);
			if (input.LA(1)=='\n'||input.LA(1)=='\r')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMENT", 41);
			LeaveRule("COMMENT", 41);
			LeaveRule_COMMENT();
		}
	}
	// $ANTLR end "COMMENT"

	public override void mTokens()
	{
		// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:8: ( T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | FLOAT | MULTILINE_COMMENT | INTEGER | IDENT | WS | COMMENT )
		int alt17=34;
		try { DebugEnterDecision(17, false);
		try
		{
			alt17 = dfa17.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(17); }
		switch (alt17)
		{
		case 1:
			DebugEnterAlt(1);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:10: T__17
			{
			DebugLocation(1, 10);
			mT__17(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:16: T__18
			{
			DebugLocation(1, 16);
			mT__18(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:22: T__19
			{
			DebugLocation(1, 22);
			mT__19(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:28: T__20
			{
			DebugLocation(1, 28);
			mT__20(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:34: T__21
			{
			DebugLocation(1, 34);
			mT__21(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:40: T__22
			{
			DebugLocation(1, 40);
			mT__22(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:46: T__23
			{
			DebugLocation(1, 46);
			mT__23(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:52: T__24
			{
			DebugLocation(1, 52);
			mT__24(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:58: T__25
			{
			DebugLocation(1, 58);
			mT__25(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:64: T__26
			{
			DebugLocation(1, 64);
			mT__26(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:70: T__27
			{
			DebugLocation(1, 70);
			mT__27(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:76: T__28
			{
			DebugLocation(1, 76);
			mT__28(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:82: T__29
			{
			DebugLocation(1, 82);
			mT__29(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:88: T__30
			{
			DebugLocation(1, 88);
			mT__30(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:94: T__31
			{
			DebugLocation(1, 94);
			mT__31(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:100: T__32
			{
			DebugLocation(1, 100);
			mT__32(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:106: T__33
			{
			DebugLocation(1, 106);
			mT__33(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:112: T__34
			{
			DebugLocation(1, 112);
			mT__34(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:118: T__35
			{
			DebugLocation(1, 118);
			mT__35(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:124: T__36
			{
			DebugLocation(1, 124);
			mT__36(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:130: T__37
			{
			DebugLocation(1, 130);
			mT__37(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:136: T__38
			{
			DebugLocation(1, 136);
			mT__38(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:142: T__39
			{
			DebugLocation(1, 142);
			mT__39(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:148: T__40
			{
			DebugLocation(1, 148);
			mT__40(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:154: T__41
			{
			DebugLocation(1, 154);
			mT__41(); 

			}
			break;
		case 26:
			DebugEnterAlt(26);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:160: T__42
			{
			DebugLocation(1, 160);
			mT__42(); 

			}
			break;
		case 27:
			DebugEnterAlt(27);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:166: T__43
			{
			DebugLocation(1, 166);
			mT__43(); 

			}
			break;
		case 28:
			DebugEnterAlt(28);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:172: T__44
			{
			DebugLocation(1, 172);
			mT__44(); 

			}
			break;
		case 29:
			DebugEnterAlt(29);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:178: FLOAT
			{
			DebugLocation(1, 178);
			mFLOAT(); 

			}
			break;
		case 30:
			DebugEnterAlt(30);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:184: MULTILINE_COMMENT
			{
			DebugLocation(1, 184);
			mMULTILINE_COMMENT(); 

			}
			break;
		case 31:
			DebugEnterAlt(31);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:202: INTEGER
			{
			DebugLocation(1, 202);
			mINTEGER(); 

			}
			break;
		case 32:
			DebugEnterAlt(32);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:210: IDENT
			{
			DebugLocation(1, 210);
			mIDENT(); 

			}
			break;
		case 33:
			DebugEnterAlt(33);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:216: WS
			{
			DebugLocation(1, 216);
			mWS(); 

			}
			break;
		case 34:
			DebugEnterAlt(34);
			// C:\\Users\\David\\Subversion\\AEGIScript\\Lang\\aegiscript.g3:1:219: COMMENT
			{
			DebugLocation(1, 219);
			mCOMMENT(); 

			}
			break;

		}

	}


	#region DFA
	DFA7 dfa7;
	DFA17 dfa17;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa7 = new DFA7(this);
		dfa17 = new DFA17(this);
	}

	private class DFA7 : DFA
	{
		private const string DFA7_eotS =
			"\5\uffff";
		private const string DFA7_eofS =
			"\5\uffff";
		private const string DFA7_minS =
			"\2\56\3\uffff";
		private const string DFA7_maxS =
			"\1\71\1\145\3\uffff";
		private const string DFA7_acceptS =
			"\2\uffff\1\2\1\1\1\3";
		private const string DFA7_specialS =
			"\5\uffff}>";
		private static readonly string[] DFA7_transitionS =
			{
				"\1\2\1\uffff\12\1",
				"\1\3\1\uffff\12\1\13\uffff\1\4\37\uffff\1\4",
				"",
				"",
				""
			};

		private static readonly short[] DFA7_eot = DFA.UnpackEncodedString(DFA7_eotS);
		private static readonly short[] DFA7_eof = DFA.UnpackEncodedString(DFA7_eofS);
		private static readonly char[] DFA7_min = DFA.UnpackEncodedStringToUnsignedChars(DFA7_minS);
		private static readonly char[] DFA7_max = DFA.UnpackEncodedStringToUnsignedChars(DFA7_maxS);
		private static readonly short[] DFA7_accept = DFA.UnpackEncodedString(DFA7_acceptS);
		private static readonly short[] DFA7_special = DFA.UnpackEncodedString(DFA7_specialS);
		private static readonly short[][] DFA7_transition;

		static DFA7()
		{
			int numStates = DFA7_transitionS.Length;
			DFA7_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA7_transition[i] = DFA.UnpackEncodedString(DFA7_transitionS[i]);
			}
		}

		public DFA7( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 7;
			this.eot = DFA7_eot;
			this.eof = DFA7_eof;
			this.min = DFA7_min;
			this.max = DFA7_max;
			this.accept = DFA7_accept;
			this.special = DFA7_special;
			this.transition = DFA7_transition;
		}

		public override string Description { get { return "91:1: FLOAT : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA17 : DFA
	{
		private const string DFA17_eotS =
			"\7\uffff\1\37\2\uffff\1\41\1\uffff\1\43\13\32\1\60\13\uffff\6\32\1\67"+
			"\2\32\1\72\2\32\1\uffff\1\32\1\76\3\32\1\103\1\uffff\1\104\1\105\1\uffff"+
			"\1\106\2\32\1\uffff\2\32\1\113\1\32\4\uffff\2\32\1\117\1\32\1\uffff\1"+
			"\121\1\122\1\32\1\uffff\1\32\2\uffff\1\125\1\32\1\uffff\1\127\1\uffff";
		private const string DFA17_eofS =
			"\130\uffff";
		private const string DFA17_minS =
			"\1\11\6\uffff\1\52\2\uffff\1\75\1\uffff\1\75\2\156\1\145\1\157\1\154"+
			"\1\146\2\157\1\162\1\141\1\150\1\56\13\uffff\1\164\1\144\1\147\1\156"+
			"\1\163\1\144\1\60\1\144\1\164\1\60\1\162\1\151\1\uffff\1\145\1\60\1\151"+
			"\1\163\1\145\1\60\1\uffff\2\60\1\uffff\1\60\1\154\1\147\1\uffff\1\156"+
			"\1\164\1\60\1\146\4\uffff\2\145\1\60\1\141\1\uffff\2\60\1\162\1\uffff"+
			"\1\156\2\uffff\1\60\1\164\1\uffff\1\60\1\uffff";
		private const string DFA17_maxS =
			"\1\172\6\uffff\1\75\2\uffff\1\75\1\uffff\1\75\2\156\1\145\1\157\1\156"+
			"\1\146\2\157\1\162\1\141\1\150\1\145\13\uffff\1\164\1\144\1\147\1\156"+
			"\1\163\1\144\1\172\1\144\1\164\1\172\1\162\1\151\1\uffff\1\145\1\172"+
			"\1\151\1\163\1\151\1\172\1\uffff\2\172\1\uffff\1\172\1\154\1\147\1\uffff"+
			"\1\156\1\164\1\172\1\146\4\uffff\2\145\1\172\1\141\1\uffff\2\172\1\162"+
			"\1\uffff\1\156\2\uffff\1\172\1\164\1\uffff\1\172\1\uffff";
		private const string DFA17_acceptS =
			"\1\uffff\1\1\1\2\1\3\1\4\1\5\1\6\1\uffff\1\11\1\12\1\uffff\1\15\15\uffff"+
			"\1\35\1\40\1\41\1\10\1\36\1\42\1\7\1\14\1\13\1\17\1\16\14\uffff\1\37"+
			"\6\uffff\1\27\2\uffff\1\32\3\uffff\1\21\4\uffff\1\26\1\30\1\31\1\33\4"+
			"\uffff\1\24\3\uffff\1\22\1\uffff\1\25\1\34\2\uffff\1\20\1\uffff\1\23";
		private const string DFA17_specialS =
			"\130\uffff}>";
		private static readonly string[] DFA17_transitionS =
			{
				"\2\33\1\uffff\2\33\22\uffff\1\33\7\uffff\1\1\1\2\1\3\1\4\1\5\1\6\1\31"+
				"\1\7\12\30\1\10\1\11\1\12\1\13\1\14\2\uffff\10\32\1\15\21\32\6\uffff"+
				"\1\16\1\17\1\20\1\32\1\21\3\32\1\22\3\32\1\23\1\24\1\25\6\32\1\26\1"+
				"\27\3\32",
				"",
				"",
				"",
				"",
				"",
				"",
				"\1\35\4\uffff\1\36\15\uffff\1\34",
				"",
				"",
				"\1\40",
				"",
				"\1\42",
				"\1\44",
				"\1\45",
				"\1\46",
				"\1\47",
				"\1\50\1\uffff\1\51",
				"\1\52",
				"\1\53",
				"\1\54",
				"\1\55",
				"\1\56",
				"\1\57",
				"\1\31\1\uffff\12\30\13\uffff\1\31\37\uffff\1\31",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\1\61",
				"\1\62",
				"\1\63",
				"\1\64",
				"\1\65",
				"\1\66",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\1\70",
				"\1\71",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\1\73",
				"\1\74",
				"",
				"\1\75",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\1\77",
				"\1\100",
				"\1\101\3\uffff\1\102",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\1\107",
				"\1\110",
				"",
				"\1\111",
				"\1\112",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\1\114",
				"",
				"",
				"",
				"",
				"\1\115",
				"\1\116",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\1\120",
				"",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\1\123",
				"",
				"\1\124",
				"",
				"",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				"\1\126",
				"",
				"\12\32\7\uffff\32\32\6\uffff\32\32",
				""
			};

		private static readonly short[] DFA17_eot = DFA.UnpackEncodedString(DFA17_eotS);
		private static readonly short[] DFA17_eof = DFA.UnpackEncodedString(DFA17_eofS);
		private static readonly char[] DFA17_min = DFA.UnpackEncodedStringToUnsignedChars(DFA17_minS);
		private static readonly char[] DFA17_max = DFA.UnpackEncodedStringToUnsignedChars(DFA17_maxS);
		private static readonly short[] DFA17_accept = DFA.UnpackEncodedString(DFA17_acceptS);
		private static readonly short[] DFA17_special = DFA.UnpackEncodedString(DFA17_specialS);
		private static readonly short[][] DFA17_transition;

		static DFA17()
		{
			int numStates = DFA17_transitionS.Length;
			DFA17_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA17_transition[i] = DFA.UnpackEncodedString(DFA17_transitionS[i]);
			}
		}

		public DFA17( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 17;
			this.eot = DFA17_eot;
			this.eof = DFA17_eof;
			this.min = DFA17_min;
			this.max = DFA17_max;
			this.accept = DFA17_accept;
			this.special = DFA17_special;
			this.transition = DFA17_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | FLOAT | MULTILINE_COMMENT | INTEGER | IDENT | WS | COMMENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}
