//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5 D:\\Eclipse\\aegiscript_live\\aegiscript.g 2013-04-26 23:01:51

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019





using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

namespace 
    AEGIScript.Lang

{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5")]
public partial class aegiscriptLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__23=23;
	public const int T__24=24;
	public const int T__25=25;
	public const int T__26=26;
	public const int T__27=27;
	public const int T__28=28;
	public const int T__29=29;
	public const int T__30=30;
	public const int T__31=31;
	public const int T__32=32;
	public const int T__33=33;
	public const int T__34=34;
	public const int T__35=35;
	public const int T__36=36;
	public const int T__37=37;
	public const int T__38=38;
	public const int T__39=39;
	public const int T__40=40;
	public const int T__41=41;
	public const int T__42=42;
	public const int T__43=43;
	public const int T__44=44;
	public const int T__45=45;
	public const int T__46=46;
	public const int T__47=47;
	public const int T__48=48;
	public const int T__49=49;
	public const int T__50=50;
	public const int T__51=51;
	public const int T__52=52;
	public const int T__53=53;
	public const int T__54=54;
	public const int T__55=55;
	public const int ACCESS=4;
	public const int ARRAY=5;
	public const int BOOL=6;
	public const int COMMENT=7;
	public const int DIGIT=8;
	public const int ESC_SEQ=9;
	public const int EXPONENT=10;
	public const int FIELD_ACCESS=11;
	public const int FLOAT=12;
	public const int FUNC=13;
	public const int HEX_DIGIT=14;
	public const int IDENT=15;
	public const int INTEGER=16;
	public const int LETTER=17;
	public const int MULTILINE_COMMENT=18;
	public const int OCTAL_ESC=19;
	public const int STRING=20;
	public const int UNICODE_ESC=21;
	public const int WS=22;
	int HIDDEN = Hidden;

    // delegates
    // delegators

	public aegiscriptLexer()
	{
		OnCreated();
	}

	public aegiscriptLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public aegiscriptLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "D:\\Eclipse\\aegiscript_live\\aegiscript.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__23();
	partial void LeaveRule_T__23();

	// $ANTLR start "T__23"
	[GrammarRule("T__23")]
	private void mT__23()
	{
		EnterRule_T__23();
		EnterRule("T__23", 1);
		TraceIn("T__23", 1);
		try
		{
			int _type = T__23;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:15:7: ( '!=' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:15:9: '!='
			{
			DebugLocation(15, 9);
			Match("!="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__23", 1);
			LeaveRule("T__23", 1);
			LeaveRule_T__23();
		}
	}
	// $ANTLR end "T__23"

	partial void EnterRule_T__24();
	partial void LeaveRule_T__24();

	// $ANTLR start "T__24"
	[GrammarRule("T__24")]
	private void mT__24()
	{
		EnterRule_T__24();
		EnterRule("T__24", 2);
		TraceIn("T__24", 2);
		try
		{
			int _type = T__24;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:16:7: ( '&&' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:16:9: '&&'
			{
			DebugLocation(16, 9);
			Match("&&"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__24", 2);
			LeaveRule("T__24", 2);
			LeaveRule_T__24();
		}
	}
	// $ANTLR end "T__24"

	partial void EnterRule_T__25();
	partial void LeaveRule_T__25();

	// $ANTLR start "T__25"
	[GrammarRule("T__25")]
	private void mT__25()
	{
		EnterRule_T__25();
		EnterRule("T__25", 3);
		TraceIn("T__25", 3);
		try
		{
			int _type = T__25;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:17:7: ( '(' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:17:9: '('
			{
			DebugLocation(17, 9);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__25", 3);
			LeaveRule("T__25", 3);
			LeaveRule_T__25();
		}
	}
	// $ANTLR end "T__25"

	partial void EnterRule_T__26();
	partial void LeaveRule_T__26();

	// $ANTLR start "T__26"
	[GrammarRule("T__26")]
	private void mT__26()
	{
		EnterRule_T__26();
		EnterRule("T__26", 4);
		TraceIn("T__26", 4);
		try
		{
			int _type = T__26;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:18:7: ( ')' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:18:9: ')'
			{
			DebugLocation(18, 9);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__26", 4);
			LeaveRule("T__26", 4);
			LeaveRule_T__26();
		}
	}
	// $ANTLR end "T__26"

	partial void EnterRule_T__27();
	partial void LeaveRule_T__27();

	// $ANTLR start "T__27"
	[GrammarRule("T__27")]
	private void mT__27()
	{
		EnterRule_T__27();
		EnterRule("T__27", 5);
		TraceIn("T__27", 5);
		try
		{
			int _type = T__27;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:19:7: ( '*' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:19:9: '*'
			{
			DebugLocation(19, 9);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__27", 5);
			LeaveRule("T__27", 5);
			LeaveRule_T__27();
		}
	}
	// $ANTLR end "T__27"

	partial void EnterRule_T__28();
	partial void LeaveRule_T__28();

	// $ANTLR start "T__28"
	[GrammarRule("T__28")]
	private void mT__28()
	{
		EnterRule_T__28();
		EnterRule("T__28", 6);
		TraceIn("T__28", 6);
		try
		{
			int _type = T__28;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:20:7: ( '+' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:20:9: '+'
			{
			DebugLocation(20, 9);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__28", 6);
			LeaveRule("T__28", 6);
			LeaveRule_T__28();
		}
	}
	// $ANTLR end "T__28"

	partial void EnterRule_T__29();
	partial void LeaveRule_T__29();

	// $ANTLR start "T__29"
	[GrammarRule("T__29")]
	private void mT__29()
	{
		EnterRule_T__29();
		EnterRule("T__29", 7);
		TraceIn("T__29", 7);
		try
		{
			int _type = T__29;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:21:7: ( ',' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:21:9: ','
			{
			DebugLocation(21, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__29", 7);
			LeaveRule("T__29", 7);
			LeaveRule_T__29();
		}
	}
	// $ANTLR end "T__29"

	partial void EnterRule_T__30();
	partial void LeaveRule_T__30();

	// $ANTLR start "T__30"
	[GrammarRule("T__30")]
	private void mT__30()
	{
		EnterRule_T__30();
		EnterRule("T__30", 8);
		TraceIn("T__30", 8);
		try
		{
			int _type = T__30;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:22:7: ( '-' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:22:9: '-'
			{
			DebugLocation(22, 9);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__30", 8);
			LeaveRule("T__30", 8);
			LeaveRule_T__30();
		}
	}
	// $ANTLR end "T__30"

	partial void EnterRule_T__31();
	partial void LeaveRule_T__31();

	// $ANTLR start "T__31"
	[GrammarRule("T__31")]
	private void mT__31()
	{
		EnterRule_T__31();
		EnterRule("T__31", 9);
		TraceIn("T__31", 9);
		try
		{
			int _type = T__31;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:23:7: ( '.' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:23:9: '.'
			{
			DebugLocation(23, 9);
			Match('.'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__31", 9);
			LeaveRule("T__31", 9);
			LeaveRule_T__31();
		}
	}
	// $ANTLR end "T__31"

	partial void EnterRule_T__32();
	partial void LeaveRule_T__32();

	// $ANTLR start "T__32"
	[GrammarRule("T__32")]
	private void mT__32()
	{
		EnterRule_T__32();
		EnterRule("T__32", 10);
		TraceIn("T__32", 10);
		try
		{
			int _type = T__32;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:24:7: ( '/' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:24:9: '/'
			{
			DebugLocation(24, 9);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__32", 10);
			LeaveRule("T__32", 10);
			LeaveRule_T__32();
		}
	}
	// $ANTLR end "T__32"

	partial void EnterRule_T__33();
	partial void LeaveRule_T__33();

	// $ANTLR start "T__33"
	[GrammarRule("T__33")]
	private void mT__33()
	{
		EnterRule_T__33();
		EnterRule("T__33", 11);
		TraceIn("T__33", 11);
		try
		{
			int _type = T__33;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:25:7: ( ':' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:25:9: ':'
			{
			DebugLocation(25, 9);
			Match(':'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__33", 11);
			LeaveRule("T__33", 11);
			LeaveRule_T__33();
		}
	}
	// $ANTLR end "T__33"

	partial void EnterRule_T__34();
	partial void LeaveRule_T__34();

	// $ANTLR start "T__34"
	[GrammarRule("T__34")]
	private void mT__34()
	{
		EnterRule_T__34();
		EnterRule("T__34", 12);
		TraceIn("T__34", 12);
		try
		{
			int _type = T__34;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:26:7: ( ';' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:26:9: ';'
			{
			DebugLocation(26, 9);
			Match(';'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__34", 12);
			LeaveRule("T__34", 12);
			LeaveRule_T__34();
		}
	}
	// $ANTLR end "T__34"

	partial void EnterRule_T__35();
	partial void LeaveRule_T__35();

	// $ANTLR start "T__35"
	[GrammarRule("T__35")]
	private void mT__35()
	{
		EnterRule_T__35();
		EnterRule("T__35", 13);
		TraceIn("T__35", 13);
		try
		{
			int _type = T__35;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:27:7: ( '<' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:27:9: '<'
			{
			DebugLocation(27, 9);
			Match('<'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__35", 13);
			LeaveRule("T__35", 13);
			LeaveRule_T__35();
		}
	}
	// $ANTLR end "T__35"

	partial void EnterRule_T__36();
	partial void LeaveRule_T__36();

	// $ANTLR start "T__36"
	[GrammarRule("T__36")]
	private void mT__36()
	{
		EnterRule_T__36();
		EnterRule("T__36", 14);
		TraceIn("T__36", 14);
		try
		{
			int _type = T__36;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:28:7: ( '<=' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:28:9: '<='
			{
			DebugLocation(28, 9);
			Match("<="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__36", 14);
			LeaveRule("T__36", 14);
			LeaveRule_T__36();
		}
	}
	// $ANTLR end "T__36"

	partial void EnterRule_T__37();
	partial void LeaveRule_T__37();

	// $ANTLR start "T__37"
	[GrammarRule("T__37")]
	private void mT__37()
	{
		EnterRule_T__37();
		EnterRule("T__37", 15);
		TraceIn("T__37", 15);
		try
		{
			int _type = T__37;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:29:7: ( '=' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:29:9: '='
			{
			DebugLocation(29, 9);
			Match('='); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__37", 15);
			LeaveRule("T__37", 15);
			LeaveRule_T__37();
		}
	}
	// $ANTLR end "T__37"

	partial void EnterRule_T__38();
	partial void LeaveRule_T__38();

	// $ANTLR start "T__38"
	[GrammarRule("T__38")]
	private void mT__38()
	{
		EnterRule_T__38();
		EnterRule("T__38", 16);
		TraceIn("T__38", 16);
		try
		{
			int _type = T__38;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:30:7: ( '==' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:30:9: '=='
			{
			DebugLocation(30, 9);
			Match("=="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__38", 16);
			LeaveRule("T__38", 16);
			LeaveRule_T__38();
		}
	}
	// $ANTLR end "T__38"

	partial void EnterRule_T__39();
	partial void LeaveRule_T__39();

	// $ANTLR start "T__39"
	[GrammarRule("T__39")]
	private void mT__39()
	{
		EnterRule_T__39();
		EnterRule("T__39", 17);
		TraceIn("T__39", 17);
		try
		{
			int _type = T__39;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:31:7: ( '>' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:31:9: '>'
			{
			DebugLocation(31, 9);
			Match('>'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__39", 17);
			LeaveRule("T__39", 17);
			LeaveRule_T__39();
		}
	}
	// $ANTLR end "T__39"

	partial void EnterRule_T__40();
	partial void LeaveRule_T__40();

	// $ANTLR start "T__40"
	[GrammarRule("T__40")]
	private void mT__40()
	{
		EnterRule_T__40();
		EnterRule("T__40", 18);
		TraceIn("T__40", 18);
		try
		{
			int _type = T__40;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:32:7: ( '>=' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:32:9: '>='
			{
			DebugLocation(32, 9);
			Match(">="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__40", 18);
			LeaveRule("T__40", 18);
			LeaveRule_T__40();
		}
	}
	// $ANTLR end "T__40"

	partial void EnterRule_T__41();
	partial void LeaveRule_T__41();

	// $ANTLR start "T__41"
	[GrammarRule("T__41")]
	private void mT__41()
	{
		EnterRule_T__41();
		EnterRule("T__41", 19);
		TraceIn("T__41", 19);
		try
		{
			int _type = T__41;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:33:7: ( 'Integer' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:33:9: 'Integer'
			{
			DebugLocation(33, 9);
			Match("Integer"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__41", 19);
			LeaveRule("T__41", 19);
			LeaveRule_T__41();
		}
	}
	// $ANTLR end "T__41"

	partial void EnterRule_T__42();
	partial void LeaveRule_T__42();

	// $ANTLR start "T__42"
	[GrammarRule("T__42")]
	private void mT__42()
	{
		EnterRule_T__42();
		EnterRule("T__42", 20);
		TraceIn("T__42", 20);
		try
		{
			int _type = T__42;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:34:7: ( '[' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:34:9: '['
			{
			DebugLocation(34, 9);
			Match('['); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__42", 20);
			LeaveRule("T__42", 20);
			LeaveRule_T__42();
		}
	}
	// $ANTLR end "T__42"

	partial void EnterRule_T__43();
	partial void LeaveRule_T__43();

	// $ANTLR start "T__43"
	[GrammarRule("T__43")]
	private void mT__43()
	{
		EnterRule_T__43();
		EnterRule("T__43", 21);
		TraceIn("T__43", 21);
		try
		{
			int _type = T__43;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:35:7: ( ']' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:35:9: ']'
			{
			DebugLocation(35, 9);
			Match(']'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__43", 21);
			LeaveRule("T__43", 21);
			LeaveRule_T__43();
		}
	}
	// $ANTLR end "T__43"

	partial void EnterRule_T__44();
	partial void LeaveRule_T__44();

	// $ANTLR start "T__44"
	[GrammarRule("T__44")]
	private void mT__44()
	{
		EnterRule_T__44();
		EnterRule("T__44", 22);
		TraceIn("T__44", 22);
		try
		{
			int _type = T__44;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:36:7: ( 'begin' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:36:9: 'begin'
			{
			DebugLocation(36, 9);
			Match("begin"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__44", 22);
			LeaveRule("T__44", 22);
			LeaveRule_T__44();
		}
	}
	// $ANTLR end "T__44"

	partial void EnterRule_T__45();
	partial void LeaveRule_T__45();

	// $ANTLR start "T__45"
	[GrammarRule("T__45")]
	private void mT__45()
	{
		EnterRule_T__45();
		EnterRule("T__45", 23);
		TraceIn("T__45", 23);
		try
		{
			int _type = T__45;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:37:7: ( 'constant' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:37:9: 'constant'
			{
			DebugLocation(37, 9);
			Match("constant"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__45", 23);
			LeaveRule("T__45", 23);
			LeaveRule_T__45();
		}
	}
	// $ANTLR end "T__45"

	partial void EnterRule_T__46();
	partial void LeaveRule_T__46();

	// $ANTLR start "T__46"
	[GrammarRule("T__46")]
	private void mT__46()
	{
		EnterRule_T__46();
		EnterRule("T__46", 24);
		TraceIn("T__46", 24);
		try
		{
			int _type = T__46;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:38:7: ( 'else' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:38:9: 'else'
			{
			DebugLocation(38, 9);
			Match("else"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__46", 24);
			LeaveRule("T__46", 24);
			LeaveRule_T__46();
		}
	}
	// $ANTLR end "T__46"

	partial void EnterRule_T__47();
	partial void LeaveRule_T__47();

	// $ANTLR start "T__47"
	[GrammarRule("T__47")]
	private void mT__47()
	{
		EnterRule_T__47();
		EnterRule("T__47", 25);
		TraceIn("T__47", 25);
		try
		{
			int _type = T__47;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:39:7: ( 'elsif' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:39:9: 'elsif'
			{
			DebugLocation(39, 9);
			Match("elsif"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__47", 25);
			LeaveRule("T__47", 25);
			LeaveRule_T__47();
		}
	}
	// $ANTLR end "T__47"

	partial void EnterRule_T__48();
	partial void LeaveRule_T__48();

	// $ANTLR start "T__48"
	[GrammarRule("T__48")]
	private void mT__48()
	{
		EnterRule_T__48();
		EnterRule("T__48", 26);
		TraceIn("T__48", 26);
		try
		{
			int _type = T__48;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:40:7: ( 'end' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:40:9: 'end'
			{
			DebugLocation(40, 9);
			Match("end"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__48", 26);
			LeaveRule("T__48", 26);
			LeaveRule_T__48();
		}
	}
	// $ANTLR end "T__48"

	partial void EnterRule_T__49();
	partial void LeaveRule_T__49();

	// $ANTLR start "T__49"
	[GrammarRule("T__49")]
	private void mT__49()
	{
		EnterRule_T__49();
		EnterRule("T__49", 27);
		TraceIn("T__49", 27);
		try
		{
			int _type = T__49;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:41:7: ( 'endif' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:41:9: 'endif'
			{
			DebugLocation(41, 9);
			Match("endif"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__49", 27);
			LeaveRule("T__49", 27);
			LeaveRule_T__49();
		}
	}
	// $ANTLR end "T__49"

	partial void EnterRule_T__50();
	partial void LeaveRule_T__50();

	// $ANTLR start "T__50"
	[GrammarRule("T__50")]
	private void mT__50()
	{
		EnterRule_T__50();
		EnterRule("T__50", 28);
		TraceIn("T__50", 28);
		try
		{
			int _type = T__50;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:42:7: ( 'if' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:42:9: 'if'
			{
			DebugLocation(42, 9);
			Match("if"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__50", 28);
			LeaveRule("T__50", 28);
			LeaveRule_T__50();
		}
	}
	// $ANTLR end "T__50"

	partial void EnterRule_T__51();
	partial void LeaveRule_T__51();

	// $ANTLR start "T__51"
	[GrammarRule("T__51")]
	private void mT__51()
	{
		EnterRule_T__51();
		EnterRule("T__51", 29);
		TraceIn("T__51", 29);
		try
		{
			int _type = T__51;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:43:7: ( 'mod' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:43:9: 'mod'
			{
			DebugLocation(43, 9);
			Match("mod"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__51", 29);
			LeaveRule("T__51", 29);
			LeaveRule_T__51();
		}
	}
	// $ANTLR end "T__51"

	partial void EnterRule_T__52();
	partial void LeaveRule_T__52();

	// $ANTLR start "T__52"
	[GrammarRule("T__52")]
	private void mT__52()
	{
		EnterRule_T__52();
		EnterRule("T__52", 30);
		TraceIn("T__52", 30);
		try
		{
			int _type = T__52;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:44:7: ( 'not' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:44:9: 'not'
			{
			DebugLocation(44, 9);
			Match("not"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__52", 30);
			LeaveRule("T__52", 30);
			LeaveRule_T__52();
		}
	}
	// $ANTLR end "T__52"

	partial void EnterRule_T__53();
	partial void LeaveRule_T__53();

	// $ANTLR start "T__53"
	[GrammarRule("T__53")]
	private void mT__53()
	{
		EnterRule_T__53();
		EnterRule("T__53", 31);
		TraceIn("T__53", 31);
		try
		{
			int _type = T__53;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:45:7: ( 'var' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:45:9: 'var'
			{
			DebugLocation(45, 9);
			Match("var"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__53", 31);
			LeaveRule("T__53", 31);
			LeaveRule_T__53();
		}
	}
	// $ANTLR end "T__53"

	partial void EnterRule_T__54();
	partial void LeaveRule_T__54();

	// $ANTLR start "T__54"
	[GrammarRule("T__54")]
	private void mT__54()
	{
		EnterRule_T__54();
		EnterRule("T__54", 32);
		TraceIn("T__54", 32);
		try
		{
			int _type = T__54;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:46:7: ( 'while' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:46:9: 'while'
			{
			DebugLocation(46, 9);
			Match("while"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__54", 32);
			LeaveRule("T__54", 32);
			LeaveRule_T__54();
		}
	}
	// $ANTLR end "T__54"

	partial void EnterRule_T__55();
	partial void LeaveRule_T__55();

	// $ANTLR start "T__55"
	[GrammarRule("T__55")]
	private void mT__55()
	{
		EnterRule_T__55();
		EnterRule("T__55", 33);
		TraceIn("T__55", 33);
		try
		{
			int _type = T__55;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:47:7: ( '||' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:47:9: '||'
			{
			DebugLocation(47, 9);
			Match("||"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__55", 33);
			LeaveRule("T__55", 33);
			LeaveRule_T__55();
		}
	}
	// $ANTLR end "T__55"

	partial void EnterRule_FUNC();
	partial void LeaveRule_FUNC();

	// $ANTLR start "FUNC"
	[GrammarRule("FUNC")]
	private void mFUNC()
	{
		EnterRule_FUNC();
		EnterRule("FUNC", 34);
		TraceIn("FUNC", 34);
		try
		{
			int _type = FUNC;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:79:2: ( 'FUNC' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:79:4: 'FUNC'
			{
			DebugLocation(79, 4);
			Match("FUNC"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FUNC", 34);
			LeaveRule("FUNC", 34);
			LeaveRule_FUNC();
		}
	}
	// $ANTLR end "FUNC"

	partial void EnterRule_ACCESS();
	partial void LeaveRule_ACCESS();

	// $ANTLR start "ACCESS"
	[GrammarRule("ACCESS")]
	private void mACCESS()
	{
		EnterRule_ACCESS();
		EnterRule("ACCESS", 35);
		TraceIn("ACCESS", 35);
		try
		{
			int _type = ACCESS;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:110:2: ( 'ACCESS' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:110:4: 'ACCESS'
			{
			DebugLocation(110, 4);
			Match("ACCESS"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ACCESS", 35);
			LeaveRule("ACCESS", 35);
			LeaveRule_ACCESS();
		}
	}
	// $ANTLR end "ACCESS"

	partial void EnterRule_FIELD_ACCESS();
	partial void LeaveRule_FIELD_ACCESS();

	// $ANTLR start "FIELD_ACCESS"
	[GrammarRule("FIELD_ACCESS")]
	private void mFIELD_ACCESS()
	{
		EnterRule_FIELD_ACCESS();
		EnterRule("FIELD_ACCESS", 36);
		TraceIn("FIELD_ACCESS", 36);
		try
		{
			int _type = FIELD_ACCESS;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:118:2: ( 'F_ACCESS' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:118:4: 'F_ACCESS'
			{
			DebugLocation(118, 4);
			Match("F_ACCESS"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FIELD_ACCESS", 36);
			LeaveRule("FIELD_ACCESS", 36);
			LeaveRule_FIELD_ACCESS();
		}
	}
	// $ANTLR end "FIELD_ACCESS"

	partial void EnterRule_ARRAY();
	partial void LeaveRule_ARRAY();

	// $ANTLR start "ARRAY"
	[GrammarRule("ARRAY")]
	private void mARRAY()
	{
		EnterRule_ARRAY();
		EnterRule("ARRAY", 37);
		TraceIn("ARRAY", 37);
		try
		{
			int _type = ARRAY;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:128:2: ( 'ARRAY' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:128:4: 'ARRAY'
			{
			DebugLocation(128, 4);
			Match("ARRAY"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ARRAY", 37);
			LeaveRule("ARRAY", 37);
			LeaveRule_ARRAY();
		}
	}
	// $ANTLR end "ARRAY"

	partial void EnterRule_BOOL();
	partial void LeaveRule_BOOL();

	// $ANTLR start "BOOL"
	[GrammarRule("BOOL")]
	private void mBOOL()
	{
		EnterRule_BOOL();
		EnterRule("BOOL", 38);
		TraceIn("BOOL", 38);
		try
		{
			int _type = BOOL;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:170:2: ( 'true' | 'false' )
			int alt1=2;
			try { DebugEnterDecision(1, false);
			int LA1_1 = input.LA(1);

			if ((LA1_1=='t'))
			{
				alt1 = 1;
			}
			else if ((LA1_1=='f'))
			{
				alt1 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 1, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:170:4: 'true'
				{
				DebugLocation(170, 4);
				Match("true"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:171:4: 'false'
				{
				DebugLocation(171, 4);
				Match("false"); 


				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BOOL", 38);
			LeaveRule("BOOL", 38);
			LeaveRule_BOOL();
		}
	}
	// $ANTLR end "BOOL"

	partial void EnterRule_FLOAT();
	partial void LeaveRule_FLOAT();

	// $ANTLR start "FLOAT"
	[GrammarRule("FLOAT")]
	private void mFLOAT()
	{
		EnterRule_FLOAT();
		EnterRule("FLOAT", 39);
		TraceIn("FLOAT", 39);
		try
		{
			int _type = FLOAT;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:175:5: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT )
			int alt8=3;
			try { DebugEnterDecision(8, false);
			try
			{
				alt8 = dfa8.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(8); }
			switch (alt8)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:175:9: ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )?
				{
				DebugLocation(175, 9);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:175:9: ( '0' .. '9' )+
				int cnt2=0;
				try { DebugEnterSubRule(2);
				while (true)
				{
					int alt2=2;
					try { DebugEnterDecision(2, false);
					int LA2_1 = input.LA(1);

					if (((LA2_1>='0' && LA2_1<='9')))
					{
						alt2 = 1;
					}


					} finally { DebugExitDecision(2); }
					switch (alt2)
					{
					case 1:
						DebugEnterAlt(1);
						// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
						{
						DebugLocation(175, 9);
						input.Consume();


						}
						break;

					default:
						if (cnt2 >= 1)
							goto loop2;

						EarlyExitException eee2 = new EarlyExitException( 2, input );
						DebugRecognitionException(eee2);
						throw eee2;
					}
					cnt2++;
				}
				loop2:
					;

				} finally { DebugExitSubRule(2); }

				DebugLocation(175, 21);
				Match('.'); 
				DebugLocation(175, 25);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:175:25: ( '0' .. '9' )*
				try { DebugEnterSubRule(3);
				while (true)
				{
					int alt3=2;
					try { DebugEnterDecision(3, false);
					int LA3_1 = input.LA(1);

					if (((LA3_1>='0' && LA3_1<='9')))
					{
						alt3 = 1;
					}


					} finally { DebugExitDecision(3); }
					switch ( alt3 )
					{
					case 1:
						DebugEnterAlt(1);
						// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
						{
						DebugLocation(175, 25);
						input.Consume();


						}
						break;

					default:
						goto loop3;
					}
				}

				loop3:
					;

				} finally { DebugExitSubRule(3); }

				DebugLocation(175, 37);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:175:37: ( EXPONENT )?
				int alt4=2;
				try { DebugEnterSubRule(4);
				try { DebugEnterDecision(4, false);
				int LA4_1 = input.LA(1);

				if ((LA4_1=='E'||LA4_1=='e'))
				{
					alt4 = 1;
				}
				} finally { DebugExitDecision(4); }
				switch (alt4)
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:175:37: EXPONENT
					{
					DebugLocation(175, 37);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(4); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:176:9: '.' ( '0' .. '9' )+ ( EXPONENT )?
				{
				DebugLocation(176, 9);
				Match('.'); 
				DebugLocation(176, 13);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:176:13: ( '0' .. '9' )+
				int cnt5=0;
				try { DebugEnterSubRule(5);
				while (true)
				{
					int alt5=2;
					try { DebugEnterDecision(5, false);
					int LA5_1 = input.LA(1);

					if (((LA5_1>='0' && LA5_1<='9')))
					{
						alt5 = 1;
					}


					} finally { DebugExitDecision(5); }
					switch (alt5)
					{
					case 1:
						DebugEnterAlt(1);
						// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
						{
						DebugLocation(176, 13);
						input.Consume();


						}
						break;

					default:
						if (cnt5 >= 1)
							goto loop5;

						EarlyExitException eee5 = new EarlyExitException( 5, input );
						DebugRecognitionException(eee5);
						throw eee5;
					}
					cnt5++;
				}
				loop5:
					;

				} finally { DebugExitSubRule(5); }

				DebugLocation(176, 25);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:176:25: ( EXPONENT )?
				int alt6=2;
				try { DebugEnterSubRule(6);
				try { DebugEnterDecision(6, false);
				int LA6_1 = input.LA(1);

				if ((LA6_1=='E'||LA6_1=='e'))
				{
					alt6 = 1;
				}
				} finally { DebugExitDecision(6); }
				switch (alt6)
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:176:25: EXPONENT
					{
					DebugLocation(176, 25);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(6); }


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:177:9: ( '0' .. '9' )+ EXPONENT
				{
				DebugLocation(177, 9);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:177:9: ( '0' .. '9' )+
				int cnt7=0;
				try { DebugEnterSubRule(7);
				while (true)
				{
					int alt7=2;
					try { DebugEnterDecision(7, false);
					int LA7_1 = input.LA(1);

					if (((LA7_1>='0' && LA7_1<='9')))
					{
						alt7 = 1;
					}


					} finally { DebugExitDecision(7); }
					switch (alt7)
					{
					case 1:
						DebugEnterAlt(1);
						// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
						{
						DebugLocation(177, 9);
						input.Consume();


						}
						break;

					default:
						if (cnt7 >= 1)
							goto loop7;

						EarlyExitException eee7 = new EarlyExitException( 7, input );
						DebugRecognitionException(eee7);
						throw eee7;
					}
					cnt7++;
				}
				loop7:
					;

				} finally { DebugExitSubRule(7); }

				DebugLocation(177, 21);
				mEXPONENT(); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FLOAT", 39);
			LeaveRule("FLOAT", 39);
			LeaveRule_FLOAT();
		}
	}
	// $ANTLR end "FLOAT"

	partial void EnterRule_MULTILINE_COMMENT();
	partial void LeaveRule_MULTILINE_COMMENT();

	// $ANTLR start "MULTILINE_COMMENT"
	[GrammarRule("MULTILINE_COMMENT")]
	private void mMULTILINE_COMMENT()
	{
		EnterRule_MULTILINE_COMMENT();
		EnterRule("MULTILINE_COMMENT", 40);
		TraceIn("MULTILINE_COMMENT", 40);
		try
		{
			int _type = MULTILINE_COMMENT;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:180:19: ( '/*' ( . )* '*/' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:180:21: '/*' ( . )* '*/'
			{
			DebugLocation(180, 21);
			Match("/*"); 

			DebugLocation(180, 26);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:180:26: ( . )*
			try { DebugEnterSubRule(9);
			while (true)
			{
				int alt9=2;
				try { DebugEnterDecision(9, false);
				int LA9_1 = input.LA(1);

				if ((LA9_1=='*'))
				{
					int LA9_2 = input.LA(2);

					if ((LA9_2=='/'))
					{
						alt9 = 2;
					}
					else if (((LA9_2>='\u0000' && LA9_2<='.')||(LA9_2>='0' && LA9_2<='\uFFFF')))
					{
						alt9 = 1;
					}


				}
				else if (((LA9_1>='\u0000' && LA9_1<=')')||(LA9_1>='+' && LA9_1<='\uFFFF')))
				{
					alt9 = 1;
				}


				} finally { DebugExitDecision(9); }
				switch ( alt9 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:180:26: .
					{
					DebugLocation(180, 26);
					MatchAny(); 

					}
					break;

				default:
					goto loop9;
				}
			}

			loop9:
				;

			} finally { DebugExitSubRule(9); }

			DebugLocation(180, 29);
			Match("*/"); 

			DebugLocation(180, 34);
			_channel = HIDDEN;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("MULTILINE_COMMENT", 40);
			LeaveRule("MULTILINE_COMMENT", 40);
			LeaveRule_MULTILINE_COMMENT();
		}
	}
	// $ANTLR end "MULTILINE_COMMENT"

	partial void EnterRule_EXPONENT();
	partial void LeaveRule_EXPONENT();

	// $ANTLR start "EXPONENT"
	[GrammarRule("EXPONENT")]
	private void mEXPONENT()
	{
		EnterRule_EXPONENT();
		EnterRule("EXPONENT", 41);
		TraceIn("EXPONENT", 41);
		try
		{
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:184:10: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:184:12: ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+
			{
			DebugLocation(184, 12);
			if (input.LA(1)=='E'||input.LA(1)=='e')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(184, 22);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:184:22: ( '+' | '-' )?
			int alt10=2;
			try { DebugEnterSubRule(10);
			try { DebugEnterDecision(10, false);
			int LA10_1 = input.LA(1);

			if ((LA10_1=='+'||LA10_1=='-'))
			{
				alt10 = 1;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
				{
				DebugLocation(184, 22);
				input.Consume();


				}
				break;

			}
			} finally { DebugExitSubRule(10); }

			DebugLocation(184, 33);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:184:33: ( '0' .. '9' )+
			int cnt11=0;
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=2;
				try { DebugEnterDecision(11, false);
				int LA11_1 = input.LA(1);

				if (((LA11_1>='0' && LA11_1<='9')))
				{
					alt11 = 1;
				}


				} finally { DebugExitDecision(11); }
				switch (alt11)
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
					{
					DebugLocation(184, 33);
					input.Consume();


					}
					break;

				default:
					if (cnt11 >= 1)
						goto loop11;

					EarlyExitException eee11 = new EarlyExitException( 11, input );
					DebugRecognitionException(eee11);
					throw eee11;
				}
				cnt11++;
			}
			loop11:
				;

			} finally { DebugExitSubRule(11); }


			}

		}
		finally
		{
			TraceOut("EXPONENT", 41);
			LeaveRule("EXPONENT", 41);
			LeaveRule_EXPONENT();
		}
	}
	// $ANTLR end "EXPONENT"

	partial void EnterRule_HEX_DIGIT();
	partial void LeaveRule_HEX_DIGIT();

	// $ANTLR start "HEX_DIGIT"
	[GrammarRule("HEX_DIGIT")]
	private void mHEX_DIGIT()
	{
		EnterRule_HEX_DIGIT();
		EnterRule("HEX_DIGIT", 42);
		TraceIn("HEX_DIGIT", 42);
		try
		{
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:187:11: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
			{
			DebugLocation(187, 11);
			if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='F')||(input.LA(1)>='a' && input.LA(1)<='f'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("HEX_DIGIT", 42);
			LeaveRule("HEX_DIGIT", 42);
			LeaveRule_HEX_DIGIT();
		}
	}
	// $ANTLR end "HEX_DIGIT"

	partial void EnterRule_ESC_SEQ();
	partial void LeaveRule_ESC_SEQ();

	// $ANTLR start "ESC_SEQ"
	[GrammarRule("ESC_SEQ")]
	private void mESC_SEQ()
	{
		EnterRule_ESC_SEQ();
		EnterRule("ESC_SEQ", 43);
		TraceIn("ESC_SEQ", 43);
		try
		{
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:191:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) | UNICODE_ESC | OCTAL_ESC )
			int alt12=3;
			try { DebugEnterDecision(12, false);
			int LA12_1 = input.LA(1);

			if ((LA12_1=='\\'))
			{
				switch (input.LA(2))
				{
				case '\"':
				case '\'':
				case '\\':
				case 'b':
				case 'f':
				case 'n':
				case 'r':
				case 't':
					{
					alt12 = 1;
					}
					break;
				case 'u':
					{
					alt12 = 2;
					}
					break;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
					{
					alt12 = 3;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 12, 1, input, 2);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 12, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(12); }
			switch (alt12)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:191:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
				{
				DebugLocation(191, 9);
				Match('\\'); 
				DebugLocation(191, 14);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:192:9: UNICODE_ESC
				{
				DebugLocation(192, 9);
				mUNICODE_ESC(); 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:193:9: OCTAL_ESC
				{
				DebugLocation(193, 9);
				mOCTAL_ESC(); 

				}
				break;

			}
		}
		finally
		{
			TraceOut("ESC_SEQ", 43);
			LeaveRule("ESC_SEQ", 43);
			LeaveRule_ESC_SEQ();
		}
	}
	// $ANTLR end "ESC_SEQ"

	partial void EnterRule_OCTAL_ESC();
	partial void LeaveRule_OCTAL_ESC();

	// $ANTLR start "OCTAL_ESC"
	[GrammarRule("OCTAL_ESC")]
	private void mOCTAL_ESC()
	{
		EnterRule_OCTAL_ESC();
		EnterRule("OCTAL_ESC", 44);
		TraceIn("OCTAL_ESC", 44);
		try
		{
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:198:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )
			int alt13=3;
			try { DebugEnterDecision(13, false);
			int LA13_1 = input.LA(1);

			if ((LA13_1=='\\'))
			{
				int LA13_2 = input.LA(2);

				if (((LA13_2>='0' && LA13_2<='3')))
				{
					int LA13_3 = input.LA(3);

					if (((LA13_3>='0' && LA13_3<='7')))
					{
						int LA13_4 = input.LA(4);

						if (((LA13_4>='0' && LA13_4<='7')))
						{
							alt13 = 1;
						}
						else
						{
							alt13 = 2;
						}
					}
					else
					{
						alt13 = 3;
					}
				}
				else if (((LA13_2>='4' && LA13_2<='7')))
				{
					int LA13_3 = input.LA(3);

					if (((LA13_3>='0' && LA13_3<='7')))
					{
						alt13 = 2;
					}
					else
					{
						alt13 = 3;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 13, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 13, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:198:9: '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(198, 9);
				Match('\\'); 
				DebugLocation(198, 14);
				input.Consume();

				DebugLocation(198, 25);
				input.Consume();

				DebugLocation(198, 36);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:199:9: '\\\\' ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(199, 9);
				Match('\\'); 
				DebugLocation(199, 14);
				input.Consume();

				DebugLocation(199, 25);
				input.Consume();


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// D:\\Eclipse\\aegiscript_live\\aegiscript.g:200:9: '\\\\' ( '0' .. '7' )
				{
				DebugLocation(200, 9);
				Match('\\'); 
				DebugLocation(200, 14);
				input.Consume();


				}
				break;

			}
		}
		finally
		{
			TraceOut("OCTAL_ESC", 44);
			LeaveRule("OCTAL_ESC", 44);
			LeaveRule_OCTAL_ESC();
		}
	}
	// $ANTLR end "OCTAL_ESC"

	partial void EnterRule_UNICODE_ESC();
	partial void LeaveRule_UNICODE_ESC();

	// $ANTLR start "UNICODE_ESC"
	[GrammarRule("UNICODE_ESC")]
	private void mUNICODE_ESC()
	{
		EnterRule_UNICODE_ESC();
		EnterRule("UNICODE_ESC", 45);
		TraceIn("UNICODE_ESC", 45);
		try
		{
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:205:5: ( '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:205:9: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT
			{
			DebugLocation(205, 9);
			Match('\\'); 
			DebugLocation(205, 14);
			Match('u'); 
			DebugLocation(205, 18);
			mHEX_DIGIT(); 
			DebugLocation(205, 28);
			mHEX_DIGIT(); 
			DebugLocation(205, 38);
			mHEX_DIGIT(); 
			DebugLocation(205, 48);
			mHEX_DIGIT(); 

			}

		}
		finally
		{
			TraceOut("UNICODE_ESC", 45);
			LeaveRule("UNICODE_ESC", 45);
			LeaveRule_UNICODE_ESC();
		}
	}
	// $ANTLR end "UNICODE_ESC"

	partial void EnterRule_LETTER();
	partial void LeaveRule_LETTER();

	// $ANTLR start "LETTER"
	[GrammarRule("LETTER")]
	private void mLETTER()
	{
		EnterRule_LETTER();
		EnterRule("LETTER", 46);
		TraceIn("LETTER", 46);
		try
		{
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:206:17: ( ( 'a' .. 'z' | 'A' .. 'Z' ) )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
			{
			DebugLocation(206, 17);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("LETTER", 46);
			LeaveRule("LETTER", 46);
			LeaveRule_LETTER();
		}
	}
	// $ANTLR end "LETTER"

	partial void EnterRule_DIGIT();
	partial void LeaveRule_DIGIT();

	// $ANTLR start "DIGIT"
	[GrammarRule("DIGIT")]
	private void mDIGIT()
	{
		EnterRule_DIGIT();
		EnterRule("DIGIT", 47);
		TraceIn("DIGIT", 47);
		try
		{
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:207:16: ( '0' .. '9' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
			{
			DebugLocation(207, 16);
			if ((input.LA(1)>='0' && input.LA(1)<='9'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("DIGIT", 47);
			LeaveRule("DIGIT", 47);
			LeaveRule_DIGIT();
		}
	}
	// $ANTLR end "DIGIT"

	partial void EnterRule_INTEGER();
	partial void LeaveRule_INTEGER();

	// $ANTLR start "INTEGER"
	[GrammarRule("INTEGER")]
	private void mINTEGER()
	{
		EnterRule_INTEGER();
		EnterRule("INTEGER", 48);
		TraceIn("INTEGER", 48);
		try
		{
			int _type = INTEGER;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:208:9: ( ( DIGIT )+ )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:208:11: ( DIGIT )+
			{
			DebugLocation(208, 11);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:208:11: ( DIGIT )+
			int cnt14=0;
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=2;
				try { DebugEnterDecision(14, false);
				int LA14_1 = input.LA(1);

				if (((LA14_1>='0' && LA14_1<='9')))
				{
					alt14 = 1;
				}


				} finally { DebugExitDecision(14); }
				switch (alt14)
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
					{
					DebugLocation(208, 11);
					input.Consume();


					}
					break;

				default:
					if (cnt14 >= 1)
						goto loop14;

					EarlyExitException eee14 = new EarlyExitException( 14, input );
					DebugRecognitionException(eee14);
					throw eee14;
				}
				cnt14++;
			}
			loop14:
				;

			} finally { DebugExitSubRule(14); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INTEGER", 48);
			LeaveRule("INTEGER", 48);
			LeaveRule_INTEGER();
		}
	}
	// $ANTLR end "INTEGER"

	partial void EnterRule_STRING();
	partial void LeaveRule_STRING();

	// $ANTLR start "STRING"
	[GrammarRule("STRING")]
	private void mSTRING()
	{
		EnterRule_STRING();
		EnterRule("STRING", 49);
		TraceIn("STRING", 49);
		try
		{
			int _type = STRING;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:210:5: ( '\"' ( ESC_SEQ |~ ( '\\\\' | '\"' ) )* '\"' )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:210:8: '\"' ( ESC_SEQ |~ ( '\\\\' | '\"' ) )* '\"'
			{
			DebugLocation(210, 8);
			Match('\"'); 
			DebugLocation(210, 12);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:210:12: ( ESC_SEQ |~ ( '\\\\' | '\"' ) )*
			try { DebugEnterSubRule(15);
			while (true)
			{
				int alt15=3;
				try { DebugEnterDecision(15, false);
				int LA15_1 = input.LA(1);

				if ((LA15_1=='\\'))
				{
					alt15 = 1;
				}
				else if (((LA15_1>='\u0000' && LA15_1<='!')||(LA15_1>='#' && LA15_1<='[')||(LA15_1>=']' && LA15_1<='\uFFFF')))
				{
					alt15 = 2;
				}


				} finally { DebugExitDecision(15); }
				switch ( alt15 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:210:14: ESC_SEQ
					{
					DebugLocation(210, 14);
					mESC_SEQ(); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:210:24: ~ ( '\\\\' | '\"' )
					{
					DebugLocation(210, 24);
					input.Consume();


					}
					break;

				default:
					goto loop15;
				}
			}

			loop15:
				;

			} finally { DebugExitSubRule(15); }

			DebugLocation(210, 39);
			Match('\"'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING", 49);
			LeaveRule("STRING", 49);
			LeaveRule_STRING();
		}
	}
	// $ANTLR end "STRING"

	partial void EnterRule_IDENT();
	partial void LeaveRule_IDENT();

	// $ANTLR start "IDENT"
	[GrammarRule("IDENT")]
	private void mIDENT()
	{
		EnterRule_IDENT();
		EnterRule("IDENT", 50);
		TraceIn("IDENT", 50);
		try
		{
			int _type = IDENT;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:212:7: ( LETTER ( LETTER | DIGIT )* )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:212:9: LETTER ( LETTER | DIGIT )*
			{
			DebugLocation(212, 9);
			mLETTER(); 
			DebugLocation(212, 16);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:212:16: ( LETTER | DIGIT )*
			try { DebugEnterSubRule(16);
			while (true)
			{
				int alt16=2;
				try { DebugEnterDecision(16, false);
				int LA16_1 = input.LA(1);

				if (((LA16_1>='0' && LA16_1<='9')||(LA16_1>='A' && LA16_1<='Z')||(LA16_1>='a' && LA16_1<='z')))
				{
					alt16 = 1;
				}


				} finally { DebugExitDecision(16); }
				switch ( alt16 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
					{
					DebugLocation(212, 16);
					input.Consume();


					}
					break;

				default:
					goto loop16;
				}
			}

			loop16:
				;

			} finally { DebugExitSubRule(16); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("IDENT", 50);
			LeaveRule("IDENT", 50);
			LeaveRule_IDENT();
		}
	}
	// $ANTLR end "IDENT"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 51);
		TraceIn("WS", 51);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:213:4: ( ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+ )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:213:6: ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+
			{
			DebugLocation(213, 6);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:213:6: ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+
			int cnt17=0;
			try { DebugEnterSubRule(17);
			while (true)
			{
				int alt17=2;
				try { DebugEnterDecision(17, false);
				int LA17_1 = input.LA(1);

				if (((LA17_1>='\t' && LA17_1<='\n')||(LA17_1>='\f' && LA17_1<='\r')||LA17_1==' '))
				{
					alt17 = 1;
				}


				} finally { DebugExitDecision(17); }
				switch (alt17)
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:
					{
					DebugLocation(213, 6);
					input.Consume();


					}
					break;

				default:
					if (cnt17 >= 1)
						goto loop17;

					EarlyExitException eee17 = new EarlyExitException( 17, input );
					DebugRecognitionException(eee17);
					throw eee17;
				}
				cnt17++;
			}
			loop17:
				;

			} finally { DebugExitSubRule(17); }

			DebugLocation(213, 41);
			_channel = HIDDEN;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 51);
			LeaveRule("WS", 51);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_COMMENT();
	partial void LeaveRule_COMMENT();

	// $ANTLR start "COMMENT"
	[GrammarRule("COMMENT")]
	private void mCOMMENT()
	{
		EnterRule_COMMENT();
		EnterRule("COMMENT", 52);
		TraceIn("COMMENT", 52);
		try
		{
			int _type = COMMENT;
			int _channel = DefaultTokenChannel;
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:214:9: ( '//' ( . )* ( '\\n' | '\\r' ) )
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:214:11: '//' ( . )* ( '\\n' | '\\r' )
			{
			DebugLocation(214, 11);
			Match("//"); 

			DebugLocation(214, 16);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:214:16: ( . )*
			try { DebugEnterSubRule(18);
			while (true)
			{
				int alt18=2;
				try { DebugEnterDecision(18, false);
				int LA18_1 = input.LA(1);

				if ((LA18_1=='\n'||LA18_1=='\r'))
				{
					alt18 = 2;
				}
				else if (((LA18_1>='\u0000' && LA18_1<='\t')||(LA18_1>='\u000B' && LA18_1<='\f')||(LA18_1>='\u000E' && LA18_1<='\uFFFF')))
				{
					alt18 = 1;
				}


				} finally { DebugExitDecision(18); }
				switch ( alt18 )
				{
				case 1:
					DebugEnterAlt(1);
					// D:\\Eclipse\\aegiscript_live\\aegiscript.g:214:16: .
					{
					DebugLocation(214, 16);
					MatchAny(); 

					}
					break;

				default:
					goto loop18;
				}
			}

			loop18:
				;

			} finally { DebugExitSubRule(18); }

			DebugLocation(214, 19);
			if (input.LA(1)=='\n'||input.LA(1)=='\r')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(214, 31);
			_channel = HIDDEN;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMENT", 52);
			LeaveRule("COMMENT", 52);
			LeaveRule_COMMENT();
		}
	}
	// $ANTLR end "COMMENT"

	public override void mTokens()
	{
		// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:8: ( T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | FUNC | ACCESS | FIELD_ACCESS | ARRAY | BOOL | FLOAT | MULTILINE_COMMENT | INTEGER | STRING | IDENT | WS | COMMENT )
		int alt19=45;
		try { DebugEnterDecision(19, false);
		try
		{
			alt19 = dfa19.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(19); }
		switch (alt19)
		{
		case 1:
			DebugEnterAlt(1);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:10: T__23
			{
			DebugLocation(1, 10);
			mT__23(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:16: T__24
			{
			DebugLocation(1, 16);
			mT__24(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:22: T__25
			{
			DebugLocation(1, 22);
			mT__25(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:28: T__26
			{
			DebugLocation(1, 28);
			mT__26(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:34: T__27
			{
			DebugLocation(1, 34);
			mT__27(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:40: T__28
			{
			DebugLocation(1, 40);
			mT__28(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:46: T__29
			{
			DebugLocation(1, 46);
			mT__29(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:52: T__30
			{
			DebugLocation(1, 52);
			mT__30(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:58: T__31
			{
			DebugLocation(1, 58);
			mT__31(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:64: T__32
			{
			DebugLocation(1, 64);
			mT__32(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:70: T__33
			{
			DebugLocation(1, 70);
			mT__33(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:76: T__34
			{
			DebugLocation(1, 76);
			mT__34(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:82: T__35
			{
			DebugLocation(1, 82);
			mT__35(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:88: T__36
			{
			DebugLocation(1, 88);
			mT__36(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:94: T__37
			{
			DebugLocation(1, 94);
			mT__37(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:100: T__38
			{
			DebugLocation(1, 100);
			mT__38(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:106: T__39
			{
			DebugLocation(1, 106);
			mT__39(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:112: T__40
			{
			DebugLocation(1, 112);
			mT__40(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:118: T__41
			{
			DebugLocation(1, 118);
			mT__41(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:124: T__42
			{
			DebugLocation(1, 124);
			mT__42(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:130: T__43
			{
			DebugLocation(1, 130);
			mT__43(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:136: T__44
			{
			DebugLocation(1, 136);
			mT__44(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:142: T__45
			{
			DebugLocation(1, 142);
			mT__45(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:148: T__46
			{
			DebugLocation(1, 148);
			mT__46(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:154: T__47
			{
			DebugLocation(1, 154);
			mT__47(); 

			}
			break;
		case 26:
			DebugEnterAlt(26);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:160: T__48
			{
			DebugLocation(1, 160);
			mT__48(); 

			}
			break;
		case 27:
			DebugEnterAlt(27);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:166: T__49
			{
			DebugLocation(1, 166);
			mT__49(); 

			}
			break;
		case 28:
			DebugEnterAlt(28);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:172: T__50
			{
			DebugLocation(1, 172);
			mT__50(); 

			}
			break;
		case 29:
			DebugEnterAlt(29);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:178: T__51
			{
			DebugLocation(1, 178);
			mT__51(); 

			}
			break;
		case 30:
			DebugEnterAlt(30);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:184: T__52
			{
			DebugLocation(1, 184);
			mT__52(); 

			}
			break;
		case 31:
			DebugEnterAlt(31);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:190: T__53
			{
			DebugLocation(1, 190);
			mT__53(); 

			}
			break;
		case 32:
			DebugEnterAlt(32);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:196: T__54
			{
			DebugLocation(1, 196);
			mT__54(); 

			}
			break;
		case 33:
			DebugEnterAlt(33);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:202: T__55
			{
			DebugLocation(1, 202);
			mT__55(); 

			}
			break;
		case 34:
			DebugEnterAlt(34);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:208: FUNC
			{
			DebugLocation(1, 208);
			mFUNC(); 

			}
			break;
		case 35:
			DebugEnterAlt(35);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:213: ACCESS
			{
			DebugLocation(1, 213);
			mACCESS(); 

			}
			break;
		case 36:
			DebugEnterAlt(36);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:220: FIELD_ACCESS
			{
			DebugLocation(1, 220);
			mFIELD_ACCESS(); 

			}
			break;
		case 37:
			DebugEnterAlt(37);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:233: ARRAY
			{
			DebugLocation(1, 233);
			mARRAY(); 

			}
			break;
		case 38:
			DebugEnterAlt(38);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:239: BOOL
			{
			DebugLocation(1, 239);
			mBOOL(); 

			}
			break;
		case 39:
			DebugEnterAlt(39);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:244: FLOAT
			{
			DebugLocation(1, 244);
			mFLOAT(); 

			}
			break;
		case 40:
			DebugEnterAlt(40);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:250: MULTILINE_COMMENT
			{
			DebugLocation(1, 250);
			mMULTILINE_COMMENT(); 

			}
			break;
		case 41:
			DebugEnterAlt(41);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:268: INTEGER
			{
			DebugLocation(1, 268);
			mINTEGER(); 

			}
			break;
		case 42:
			DebugEnterAlt(42);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:276: STRING
			{
			DebugLocation(1, 276);
			mSTRING(); 

			}
			break;
		case 43:
			DebugEnterAlt(43);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:283: IDENT
			{
			DebugLocation(1, 283);
			mIDENT(); 

			}
			break;
		case 44:
			DebugEnterAlt(44);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:289: WS
			{
			DebugLocation(1, 289);
			mWS(); 

			}
			break;
		case 45:
			DebugEnterAlt(45);
			// D:\\Eclipse\\aegiscript_live\\aegiscript.g:1:292: COMMENT
			{
			DebugLocation(1, 292);
			mCOMMENT(); 

			}
			break;

		}

	}


	#region DFA
	DFA8 dfa8;
	DFA19 dfa19;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa8 = new DFA8(this);
		dfa19 = new DFA19(this);
	}

	private class DFA8 : DFA
	{
		private const string DFA8_eotS =
			"\x5\xFFFF";
		private const string DFA8_eofS =
			"\x5\xFFFF";
		private const string DFA8_minS =
			"\x2\x2E\x3\xFFFF";
		private const string DFA8_maxS =
			"\x1\x39\x1\x65\x3\xFFFF";
		private const string DFA8_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1\x1\x3";
		private const string DFA8_specialS =
			"\x5\xFFFF}>";
		private static readonly string[] DFA8_transitionS =
			{
				"\x1\x2\x1\xFFFF\xA\x1",
				"\x1\x3\x1\xFFFF\xA\x1\xB\xFFFF\x1\x4\x1F\xFFFF\x1\x4",
				"",
				"",
				""
			};

		private static readonly short[] DFA8_eot = DFA.UnpackEncodedString(DFA8_eotS);
		private static readonly short[] DFA8_eof = DFA.UnpackEncodedString(DFA8_eofS);
		private static readonly char[] DFA8_min = DFA.UnpackEncodedStringToUnsignedChars(DFA8_minS);
		private static readonly char[] DFA8_max = DFA.UnpackEncodedStringToUnsignedChars(DFA8_maxS);
		private static readonly short[] DFA8_accept = DFA.UnpackEncodedString(DFA8_acceptS);
		private static readonly short[] DFA8_special = DFA.UnpackEncodedString(DFA8_specialS);
		private static readonly short[][] DFA8_transition;

		static DFA8()
		{
			int numStates = DFA8_transitionS.Length;
			DFA8_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA8_transition[i] = DFA.UnpackEncodedString(DFA8_transitionS[i]);
			}
		}

		public DFA8( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 8;
			this.eot = DFA8_eot;
			this.eof = DFA8_eof;
			this.min = DFA8_min;
			this.max = DFA8_max;
			this.accept = DFA8_accept;
			this.special = DFA8_special;
			this.transition = DFA8_transition;
		}

		public override string Description { get { return "174:1: FLOAT : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA19 : DFA
	{
		private const string DFA19_eotS =
			"\x9\xFFFF\x1\x24\x1\x28\x2\xFFFF\x1\x2A\x1\x2C\x1\x2E\x1\x22\x2\xFFFF"+
			"\x8\x22\x1\xFFFF\x4\x22\x1\x3F\xE\xFFFF\x5\x22\x1\x45\x5\x22\x1\xFFFF"+
			"\x4\x22\x1\xFFFF\x4\x22\x1\x55\x1\xFFFF\x1\x56\x1\x57\x1\x58\x9\x22\x1"+
			"\x62\x2\x22\x4\xFFFF\x1\x22\x1\x66\x2\x22\x1\x69\x2\x22\x1\x6C\x1\x22"+
			"\x1\xFFFF\x1\x6E\x1\x6F\x1\x70\x1\xFFFF\x1\x22\x1\x72\x1\xFFFF\x1\x69"+
			"\x1\x22\x1\xFFFF\x1\x22\x3\xFFFF\x1\x75\x1\xFFFF\x1\x76\x1\x22\x2\xFFFF"+
			"\x1\x78\x1\xFFFF";
		private const string DFA19_eofS =
			"\x79\xFFFF";
		private const string DFA19_minS =
			"\x1\x9\x8\xFFFF\x1\x30\x1\x2A\x2\xFFFF\x3\x3D\x1\x6E\x2\xFFFF\x1\x65"+
			"\x1\x6F\x1\x6C\x1\x66\x2\x6F\x1\x61\x1\x68\x1\xFFFF\x1\x55\x1\x43\x1"+
			"\x72\x1\x61\x1\x2E\xE\xFFFF\x1\x74\x1\x67\x1\x6E\x1\x73\x1\x64\x1\x30"+
			"\x1\x64\x1\x74\x1\x72\x1\x69\x1\x4E\x1\xFFFF\x1\x43\x1\x52\x1\x75\x1"+
			"\x6C\x1\xFFFF\x1\x65\x1\x69\x1\x73\x1\x65\x1\x30\x1\xFFFF\x3\x30\x1\x6C"+
			"\x1\x43\x1\x45\x1\x41\x1\x65\x1\x73\x1\x67\x1\x6E\x1\x74\x1\x30\x2\x66"+
			"\x4\xFFFF\x1\x65\x1\x30\x1\x53\x1\x59\x1\x30\x2\x65\x1\x30\x1\x61\x1"+
			"\xFFFF\x3\x30\x1\xFFFF\x1\x53\x1\x30\x1\xFFFF\x1\x30\x1\x72\x1\xFFFF"+
			"\x1\x6E\x3\xFFFF\x1\x30\x1\xFFFF\x1\x30\x1\x74\x2\xFFFF\x1\x30\x1\xFFFF";
		private const string DFA19_maxS =
			"\x1\x7C\x8\xFFFF\x1\x39\x1\x2F\x2\xFFFF\x3\x3D\x1\x6E\x2\xFFFF\x1\x65"+
			"\x1\x6F\x1\x6E\x1\x66\x2\x6F\x1\x61\x1\x68\x1\xFFFF\x1\x5F\x1\x52\x1"+
			"\x72\x1\x61\x1\x65\xE\xFFFF\x1\x74\x1\x67\x1\x6E\x1\x73\x1\x64\x1\x7A"+
			"\x1\x64\x1\x74\x1\x72\x1\x69\x1\x4E\x1\xFFFF\x1\x43\x1\x52\x1\x75\x1"+
			"\x6C\x1\xFFFF\x1\x65\x1\x69\x1\x73\x1\x69\x1\x7A\x1\xFFFF\x3\x7A\x1\x6C"+
			"\x1\x43\x1\x45\x1\x41\x1\x65\x1\x73\x1\x67\x1\x6E\x1\x74\x1\x7A\x2\x66"+
			"\x4\xFFFF\x1\x65\x1\x7A\x1\x53\x1\x59\x1\x7A\x2\x65\x1\x7A\x1\x61\x1"+
			"\xFFFF\x3\x7A\x1\xFFFF\x1\x53\x1\x7A\x1\xFFFF\x1\x7A\x1\x72\x1\xFFFF"+
			"\x1\x6E\x3\xFFFF\x1\x7A\x1\xFFFF\x1\x7A\x1\x74\x2\xFFFF\x1\x7A\x1\xFFFF";
		private const string DFA19_acceptS =
			"\x1\xFFFF\x1\x1\x1\x2\x1\x3\x1\x4\x1\x5\x1\x6\x1\x7\x1\x8\x2\xFFFF\x1"+
			"\xB\x1\xC\x4\xFFFF\x1\x14\x1\x15\x8\xFFFF\x1\x21\x5\xFFFF\x1\x2A\x1\x2B"+
			"\x1\x2C\x1\x9\x1\x27\x1\x28\x1\x2D\x1\xA\x1\xE\x1\xD\x1\x10\x1\xF\x1"+
			"\x12\x1\x11\xB\xFFFF\x1\x24\x4\xFFFF\x1\x29\x5\xFFFF\x1\x1C\xF\xFFFF"+
			"\x1\x1A\x1\x1D\x1\x1E\x1\x1F\x9\xFFFF\x1\x18\x3\xFFFF\x1\x22\x2\xFFFF"+
			"\x1\x26\x2\xFFFF\x1\x16\x1\xFFFF\x1\x19\x1\x1B\x1\x20\x1\xFFFF\x1\x25"+
			"\x2\xFFFF\x1\x23\x1\x13\x1\xFFFF\x1\x17";
		private const string DFA19_specialS =
			"\x79\xFFFF}>";
		private static readonly string[] DFA19_transitionS =
			{
				"\x2\x23\x1\xFFFF\x2\x23\x12\xFFFF\x1\x23\x1\x1\x1\x21\x3\xFFFF\x1\x2"+
				"\x1\xFFFF\x1\x3\x1\x4\x1\x5\x1\x6\x1\x7\x1\x8\x1\x9\x1\xA\xA\x20\x1"+
				"\xB\x1\xC\x1\xD\x1\xE\x1\xF\x2\xFFFF\x1\x1D\x4\x22\x1\x1C\x2\x22\x1"+
				"\x10\x11\x22\x1\x11\x1\xFFFF\x1\x12\x3\xFFFF\x1\x22\x1\x13\x1\x14\x1"+
				"\x22\x1\x15\x1\x1F\x2\x22\x1\x16\x3\x22\x1\x17\x1\x18\x5\x22\x1\x1E"+
				"\x1\x22\x1\x19\x1\x1A\x3\x22\x1\xFFFF\x1\x1B",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\xA\x25",
				"\x1\x26\x4\xFFFF\x1\x27",
				"",
				"",
				"\x1\x29",
				"\x1\x2B",
				"\x1\x2D",
				"\x1\x2F",
				"",
				"",
				"\x1\x30",
				"\x1\x31",
				"\x1\x32\x1\xFFFF\x1\x33",
				"\x1\x34",
				"\x1\x35",
				"\x1\x36",
				"\x1\x37",
				"\x1\x38",
				"",
				"\x1\x39\x9\xFFFF\x1\x3A",
				"\x1\x3B\xE\xFFFF\x1\x3C",
				"\x1\x3D",
				"\x1\x3E",
				"\x1\x25\x1\xFFFF\xA\x20\xB\xFFFF\x1\x25\x1F\xFFFF\x1\x25",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x40",
				"\x1\x41",
				"\x1\x42",
				"\x1\x43",
				"\x1\x44",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\x1\x46",
				"\x1\x47",
				"\x1\x48",
				"\x1\x49",
				"\x1\x4A",
				"",
				"\x1\x4B",
				"\x1\x4C",
				"\x1\x4D",
				"\x1\x4E",
				"",
				"\x1\x4F",
				"\x1\x50",
				"\x1\x51",
				"\x1\x52\x3\xFFFF\x1\x53",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x8\x22\x1\x54\x11\x22",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\x1\x59",
				"\x1\x5A",
				"\x1\x5B",
				"\x1\x5C",
				"\x1\x5D",
				"\x1\x5E",
				"\x1\x5F",
				"\x1\x60",
				"\x1\x61",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\x1\x63",
				"\x1\x64",
				"",
				"",
				"",
				"",
				"\x1\x65",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\x1\x67",
				"\x1\x68",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\x1\x6A",
				"\x1\x6B",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\x1\x6D",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"",
				"\x1\x71",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\x1\x73",
				"",
				"\x1\x74",
				"",
				"",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				"\x1\x77",
				"",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x6\xFFFF\x1A\x22",
				""
			};

		private static readonly short[] DFA19_eot = DFA.UnpackEncodedString(DFA19_eotS);
		private static readonly short[] DFA19_eof = DFA.UnpackEncodedString(DFA19_eofS);
		private static readonly char[] DFA19_min = DFA.UnpackEncodedStringToUnsignedChars(DFA19_minS);
		private static readonly char[] DFA19_max = DFA.UnpackEncodedStringToUnsignedChars(DFA19_maxS);
		private static readonly short[] DFA19_accept = DFA.UnpackEncodedString(DFA19_acceptS);
		private static readonly short[] DFA19_special = DFA.UnpackEncodedString(DFA19_specialS);
		private static readonly short[][] DFA19_transition;

		static DFA19()
		{
			int numStates = DFA19_transitionS.Length;
			DFA19_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA19_transition[i] = DFA.UnpackEncodedString(DFA19_transitionS[i]);
			}
		}

		public DFA19( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 19;
			this.eot = DFA19_eot;
			this.eof = DFA19_eof;
			this.min = DFA19_min;
			this.max = DFA19_max;
			this.accept = DFA19_accept;
			this.special = DFA19_special;
			this.transition = DFA19_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | FUNC | ACCESS | FIELD_ACCESS | ARRAY | BOOL | FLOAT | MULTILINE_COMMENT | INTEGER | STRING | IDENT | WS | COMMENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}

} // namespace 

